### ISSUE TITLE
kpsewhich -var-value TEXMFHOME is not a real directory on OS X

### ISSUE THREAD

**Issue by zechen11** [michal-h21/make4ht#1]
I want to install make4hl on OS X 10.10.
But "cd `kpsewhich -var-value TEXMFHOME`" returns as below:
-bash: cd: /Users/huangzechen/Library/texmf: No such file or directory

**Comment by michal-h21** [comment]
If the TEXMFHOME directory doesn't exist yet, you need to create it. I've
added note about this to the README.

2015-02-08 14:37 GMT+01:00 zechen11 <notifications@github.com>:
