### ISSUE TITLE
Feature request: minted

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#100]
Is it possible to add support for the [minted package](https://www.overleaf.com/learn/latex/Code_Highlighting_with_minted) in `make4ht`?

`minted` is a modern alternative to `lstlisting` which allows more structured, colourful and complete syntax highlighting. 

As of now, make4ht complains when using minted:
```
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename	Line	Message
[ERROR]   htlatex: ./markup.tex 	44	 Package minted Error: You must invoke LaTeX with the -shell-escape flag.
[ERROR]   htlatex: ./markup.tex 	45	 Package minted Error: You must have `pygmentize' installed to use this packag
[ERROR]   htlatex: ./markup.tex 	50	 Package catchfile Error: File `_minted-markup/default.pygstyle' not found.
[ERROR]   htlatex: ./markup.tex 	50	 Package catchfile Error: File `_minted-markup/default.pygstyle' not found.
[ERROR]   htlatex: ./markup.tex 	73	 Package minted Error: Cannot find Pygments style default.
[ERROR]   htlatex: ./markup.tex 	73	 Package minted Error: Missing Pygments output; \inputminted was
```

**Comment by michal-h21** [comment]
Minted is supported, I am using it myself in TeX4ht documentation. But it requires the '-s' option for make4ht:

    make4ht -s foo.tex

**Comment by yalguzaq** [comment]
Sorry, I googled it before and could not find anything on this. Thanks! Removing the threat.
