### ISSUE TITLE
minted css colors based on IDs, not class names

### ISSUE THREAD

**Issue by iabarus** [michal-h21/make4ht#103]
The package `minted`, when translated to CSS, uses HTML id's to color the code:

![image](https://user-images.githubusercontent.com/116675649/205267016-b57faf91-a599-4aab-b4ef-c8b596c43439.png)
`<span id='textcolor5'><span class='ectt-1000'>import</span></span><span class='ectt-1000'> </span><span id='textcolor6'><span class='ectt-1000'>configparser</span></span><span id='textcolor7'><span class='ectt-1000'>,</span></span><span class='ectt-1000'> </span><span id='textcolor8'><span class='ectt-1000'>boto3</span></span><span id='textcolor9'><span class='ectt-1000'>,</span></span><span class='ectt-1000'> </span><span id='textcolor10'><span class='ectt-1000'>os</span></span><span id='textcolor11'><span class='ectt-1000'>,</span></span><span class='ectt-1000'> </span><span id='textcolor12'><span class='ectt-1000'>time</span></span><span id='textcolor13'><span class='ectt-1000'>,</span></span><span class='ectt-1000'> </span><span id='textcolor14'><span class='ectt-1000'>json</span></span> `

I would argue that this is a bad design since combining several translated files into one often causes conflicts in definitions. See for instance [this question](https://tex.stackexchange.com/questions/660994/make4ht-generic-css/661062?noredirect=1#comment1644597_661062).

Would it be possible to color the code chunks using CSS classes instead of HTML IDs?

**Comment by michal-h21** [comment]
There are two solutions for this issue:

- the `join_colors` extension - it does what you want, it replaces id's for colors with a class for each color
- the `inlinecss` extension, which is included in the DEV version of `make4ht`. It parses the CSS file for ID rules, and places the style information to the HTML file.

`join_colors` should be already available in the CTAN version, so you can use that with:

     $ make4ht -f html5+join_colors filename.tex
