### ISSUE TITLE
runscript.tlu ERROR

### ISSUE THREAD

**Issue by balakrishnan1978** [michal-h21/make4ht#119]
I have installed **TeXLive-2023 on Windows** and updated **tlmgr update --all --self update** found the below error when running **make4ht filename.tex**.

**D:\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 1:**
**texlua d:\texlive\2023\texmf-dist\scripts\make4ht\make4ht**

I have just tried `make4ht` also and showing the above error. How to rectify this?

**Comment by michal-h21** [comment]
Is it all output you got? No status messages or anything? Can you run this command? 

    $ texlua d:\texlive\2023\texmf-dist\scripts\make4ht\make4ht -m draft -a debug filename.tex

Does it do anything?

**Comment by balakrishnan1978** [comment]
@michal-h21 Thanks for your quick action. Above your command is working fine and not showing any error messages(only warnings showing).

But when i have using **\section** LaTeX Command it's not running and system hanging. I have used 'Frontiersinhardvard' opensource latex template(available **https://www.frontiersin.org/guidelines/author-guidelines**).

**Comment by michal-h21** [comment]
I don't know about this class, but from what I see it doesn't load any standard LaTeX class and defines some basic commands on it's own. I would need to find a time to write a support for that class, as it even isn't on CTAN.

**Comment by balakrishnan1978** [comment]
@michal-h21 : Yes, I agree with your comments. But it's running in `LaTeX/PdfLaTeX/XeLaTeX/LuaLaTeX` well and produce output. Only not working only **Make4HT** and hanging in only **\section** LaTeX command. Without **\section** command **Make4HT** working good.

**Comment by michal-h21** [comment]
Yes, it doesn't work with TeX4ht, because  it will need a pretty masive configuration file, as it defines so many things on its own. When I ran the `frontiers.tex` file, it even finished with a fatal error, because of subfigures and captions.

**Comment by balakrishnan1978** [comment]
When I've removed \MakeUpperCase in the \section tag system is not hanging.
\begin{algorithm} with \caption tex4ht showing error. How to rectify this error?
Thanks and Regards,bala
88707510677401588566 

    On Sunday, April 23, 2023 at 10:16:14 PM GMT+5:30, Michal Hoftich ***@***.***> wrote:  
 
 


Yes, it doesn't work with TeX4ht, because it will need a pretty masive configuration file, as it defines so many things on its own. When I ran the frontiers.tex file, it even finished with a fatal error, because of subfigures and captions.

**Comment by balakrishnan1978** [comment]
Dear Michael,
Any possibilities to support frontiers latex templates fully in TeX4ht(Make4HT)?
OR
to support subfigures and captions packages in TeX4HT(Make4HT)?
Regards,bala

On Sunday, April 23, 2023 at 10:16:14 PM GMT+5:30, Michal Hoftich ***@***.***> wrote:
 
 
 


Yes, it doesn't work with TeX4ht, because it will need a pretty masive configuration file, as it defines so many things on its own. When I ran the frontiers.tex file, it even finished with a fatal error, because of subfigures and captions.

**Comment by balakrishnan1978** [comment]
Dear Michal,
Thanks for your reply and .4ht file. Take Care of your health.
I have attached the MWE .rar file for checking the algorithm. If you've time kindly look into this.
Thanks,bala
    On Thursday, April 27, 2023 at 09:52:42 PM GMT+5:30, Michal Hoftich ***@***.***> wrote:  
 
 


Sorry, I am ill right now, so it may take some time. Anyway, it seems that \MakeUppercase really was one serious issue. When I removed it, I can compile the MWE from here without errors. The following configuration file, FrontiersinHarvard.4ht, produces correct tags for section headings.
\ifdefined\listoffigures\else\def\listoffigures{\relax}\fi
\ifdefined\listoftables\else\def\listoftables{\relax}\fi
\input article.4ht
Do you have a MWE with this algorithm error?

**Comment by balakrishnan1978** [comment]
Dear Michal,
It's good to hear you are come back.
I've attached the algori.tex and algori.pdf file for your testing..
Thanks and Regards,bala 

    On Tuesday, May 2, 2023 at 01:41:01 PM GMT+5:30, Michal Hoftich ***@***.***> wrote:  
 
 


@balakrishnan1978 I am finally OK, thanks. I cannot see the .rar file, unfortunately.

**Comment by balakrishnan1978** [comment]
[algori.pdf](https://github.com/michal-h21/make4ht/files/11376147/algori.pdf)
Dear Michal,

LaTeX file is also attachment is not possible. So I have pasted here..

\documentclass[utf8]{FrontiersinHarvard} 
\usepackage{url,hyperref,microtype,algorithmic,algorithm}

\newcommand{\set}{\mathcal{S}}
\def\firstAuthorLast{}
\def\Authors{Yu}
\def\Address{Department of Electrical and Computer Engineering}
\def\corrAuthor{Yu}
\def\corrEmail{@rice.edu}

\begin{document}
\onecolumn
\title[Hypergraphs with Edge-Dependent Weights]{Hypergraphs with Edge-Dependent Weights} 
\author[\firstAuthorLast ]{\Authors}
\address{}
\correspondance{}
\extraAuth{}
\maketitle

It has been shown in~{veldt2020hypergraph} that all hypergraphs with submodular cardinality-based splitting functions are graph reducible. 
Our earlier work~{zhu2022ans} has generalized the conclusion to hypergraphs with submodular EDVW-based splitting functions.
In the following section, we propose a $1$-spectral clustering algorithm for all submodular hypergraphs that are graph reducible including those EDVW-based ones, which are the focus of this paper.

\begin{algorithm}[t]
\caption{$1$-spectral clustering for hypergraphs with EDVW}\label{alg:spec_cluster}
\begin{algorithmic}[1]
\STATE \textbf{Input:} hypergraph with EDVW $\mathcal{H}=(\mathcal{V},\mathcal{E},\mu,\kappa,\{\gamma_e\})$
\STATE Convert $\mathcal{H}$ to a submodular hypergraph by constructing submodular splitting functions based on~1\STATE Compute the second eigenvector of the hypergraph $1$-Laplacian via the minimization of $R_1()$ in~1
\end{algorithmic}
\end{algorithm}

The pipeline for the $1$-spectral clustering algorithm is summarized in Algorithm~\ref{alg:ipm}. 

\begin{algorithm}[t]
\caption{IPM-based minimization of $R_1()$~\citep{hein2010inverse, li2018submodular}}\label{alg:ipm}
\begin{algorithmic}[1]
\STATE\textbf{Input:} submodular hypergraph $\mathcal{H}=(\mathcal{V},\mathcal{E},\mu,\{w_e\})$ with $N$ vertices, accuracy $\epsilon$
\STATE\textbf{repeat} 
\STATE $\lambda'\leftarrow\lambda,\lambda\leftarrow R_1()$
\STATE\textbf{until} $\frac{|\lambda-\lambda'|}{\lambda'}<\epsilon$
\STATE\textbf{Output:}
\end{algorithmic}
\end{algorithm}
\end{document}

Please let me know this format is OK?

**Comment by balakrishnan1978** [comment]
[algori.txt](https://github.com/michal-h21/make4ht/files/11376166/algori.txt)
Please ignore above tex file (all the latex commands are converted to respective UTF format. I have just renamed **algori.tex** to **algori.txt**. Please find attached the same. Hope this will work for testing.

Regards,
bala

**Comment by michal-h21** [comment]
I don't get errors in running this example, but found some errors in the frontiers.tex file from the template. This version of `FrontiersinHarvard.4ht` should fix it:

```
\ifdefined\listoffigures\else\def\listoffigures{\relax}\fi
\ifdefined\listoftables\else\def\listoftables{\relax}\fi

\def\section{%
  \@startsection{section}{1}{\z@}
  {-10\p@ plus -3\p@}{3\p@}
  {\reset@font\raggedright\helveticabold\fontsize{13}{13}\color{black}\selectfont}}

\renewenvironment{subfigure}{\ifsub@@figure\global\sub@@figurefalse\stepcounter{figure}\fi%
 \@float{subfigure}}{\end@float}
\renewenvironment{subfigure*}{\ifsub@@figure\global\sub@@figurefalse\stepcounter{figure}\fi%
 \@float{subfigure}}{\end@float}

\input article.4ht

```

I also had to fix error with the `lineno` package, using this `lineno.4ht` file:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% lineno.4ht                            2009-05-21-09:32 %
% Copyright (C) 2000--2009       Eitan M. Gurari         %
%                                                        %
% This work may be distributed and/or modified under the %
% conditions of the LaTeX Project Public License, either %
% version 1.3c of this license or (at your option) any   %
% later version. The latest version of this license is   %
% in                                                     %
%   http://www.latex-project.org/lppl.txt                %
% and version 1.3c or later is part of all distributions %
% of LaTeX version 2005/12/01 or later.                  %
%                                                        %
% This work has the LPPL maintenance status "maintained".%
%                                                        %
% This Current Maintainer of this work                   %
% is Eitan M. Gurari.                                    %
%                                                        %
% If you modify this program your changing its signature %
% with a directive of the following form will be         %
% appreciated.                                           %
%            \message{signature}                         %
%                                                        %
%                             gurari@cse.ohio-state.edu  %
%                 http://www.cse.ohio-state.edu/~gurari  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\immediate\write-1{version 2009-05-21-09:32}


\let\:tempc\linelabel
\pend:defI\:tempc{\let\sv:efloat\end@float \HRestore\end@float  }
\append:defI\:tempc{\let\end@float\sv:efloat  }
\HLet\linelabel\:tempc


\def\:tempc{\@tempdima\dp\@cclv \unvbox\@cclv
   \sbox\@tempboxa{\hbox to\z@{\a:lineno\makeLineNumber\b:lineno}}%
   \stepcounter{linenumber}%
   \dp\@tempboxa=\@tempdima\ht\@tempboxa=\z@
   \nointerlineskip\kern-\@tempdima\box\@tempboxa
   \ifnum\outputpenalty=-\linenopenaltypar\else
       \@tempcnta\outputpenalty
       \advance\@tempcnta -\linenopenalty
       \penalty\@tempcnta
   \fi
   }
\HLet\MakeLineNo\:tempc
\NewConfigure{lineno}{2}

\HLet\linenumbers\relax
\LineNumbersfalse                              % v4.00

\Hinput{lineno}
\endinput


```

**Comment by balakrishnan1978** [comment]
Dear Michal,

Thanks for the files and it's working fine. I have another issue in equation and raise in separate ticket here.

Regards,
bala
