### ISSUE TITLE
Trouble on OSX High Sierra 2018

### ISSUE THREAD

**Issue by mpomeran** [michal-h21/make4ht#12]
Hello, 
I keep getting the following error after updating to TL 2018 version: 
$ make4ht -uf html5 Yaqut.tex
Output dir: 	
Compiler: 	latex
Latex options: 	 -jobname=Yaqut 
tex4ht.sty :	xhtml,,charset=utf-8
tex4ht	 -cmozhtf -utf8
build_file	Yaqut.mk4
Output format	html5
/Library/TeX/texbin/make4ht:62: attempt to index local 'formatter' (a nil value)

**Comment by mpomeran** [comment]
Dear Michal, 

Thank you that works very well! 
One issue I'm struggling with now is that the formatting of the odt file looks very different than it did in TL 2017 version. I'm not sure why the section headings now run together in my odt file. Can I adjust the formatting of the odt file from the make4ht end (adjusting the font, spacing etc.) ? Also capitalizing the author name would be nice too. Here's the pdf I'm aiming to replicate in odt... 


[IbnHijja.docx](https://github.com/michal-h21/make4ht/files/2019967/IbnHijja.docx)
[IbnHijja.pdf](https://github.com/michal-h21/make4ht/files/2019968/IbnHijja.pdf)

Thanks so much, 
Maurice

**Comment by mpomeran** [comment]
Hello again, Michal, 
I see that the problem is likely the memoir package that I'm adapting. When I deleted that, the headers and the rest of the formatting came through much better in the odt file. I wonder is there a way for me to keep using the memoir package? 

Thanks very much, and sorry for the repeated questions, 
Maurice

**Comment by michal-h21** [comment]
Hello Maurice,

Memoir update in TL 2018 broke tex4ht support. See https://tex.stackexchange.com/a/429848/2891 for some details. The updated version of tex4ht support for Memoir should be in TL soon.

Best regards,
Michal
