### ISSUE TITLE
All Equations maintain same Input Format - Equation Cross-Links

### ISSUE THREAD

**Issue by balakrishnan1978** [michal-h21/make4ht#120]
Hi,

I would like to maintain all the **display and inline equations** are no need to convert **mathml/svg or any other format**. Need to maintain as per **source Input** file. Please find attached the Equation.txt file (rename **.txt** to **.tex**) and find attached the eq-config.txt file (rename **Eq-config.txt** to **Eq-config.cfg**).

Equations are maintaing as per source Input file. But Equation Cross-Links is not correct. How to get expected output?

My Terminal Command is:

**make4ht -ux -a debug -c Eq-config.cfg Equation.tex '' '-p'**

[Eq-config.txt](https://github.com/michal-h21/make4ht/files/11389701/Eq-config.txt)
[Equation.txt](https://github.com/michal-h21/make4ht/files/11389693/Equation.txt)

**Comment by michal-h21** [comment]
When you keep your math as verbatim LaTeX code, cross references cannot work. There are some workarounds, for example this: https://tex.stackexchange.com/a/597913/2891.

**Comment by balakrishnan1978** [comment]
@michal-h21 It's possible to maintain math should be **all math in verbatim** as well as **MathML**. So, cross references will work. I'm correct or not and it's possible to fix in TeX4HT? Please advise...

**Comment by michal-h21** [comment]
Maybe try to add something like this to your config file:

      \renewcommand\eqref[1]{\texttt{\string\eqref\{\detokenize{#1}\}}}

This will keep the `\eqref` command in the HTML output even if you use it outside math.
