### ISSUE TITLE
uline in ulem package

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#131]
I see from other issues that the ulem package is implemented. But I can't seem to get it to work when converting too DocBook. Is \uline{} implemented for DocBook? I would like to see <emphasis role="underline"> in Docbook when using \uline.

Best regards
Hans

**Comment by michal-h21** [comment]
Most configurations are missing in Docbook. I can add `ulem` configuration easily, hopefully. Does the following configuration produce the expected output? If yes, I will update TeX4th sources:
```

\Preamble{xhtml}
\Configure{uline}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{uuline}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{sout}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{xout}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{uwave}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{dashuline}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\Configure{dotuline}{\HCode{<emphasis role="underline">}}{\HCode{</emphasis>}}
\begin{document}
\EndPreamble
```

**Comment by hcf-n** [comment]
Works as expected. Thanks!

**Comment by michal-h21** [comment]
Great! I've added that to TeX4ht sources, so it should work soon out of the box.
