### ISSUE TITLE
Tabular breaks tikzcd diagram

### ISSUE THREAD

**Issue by gnull** [michal-h21/make4ht#143]
I'm running `make4ht -l -sm draft -f html5 main.tex` with the file:

```latex
\documentclass{article}

\usepackage{tikz-cd}

\begin{document}

\begin{tikzcd}
  \begin{tabular}{c}
    hey \\
    sup
  \end{tabular}
\end{tikzcd}

\end{document}
```

Which renders as expected in pdf, but produces garbage in html.

| ![image](https://github.com/michal-h21/make4ht/assets/7102119/093fbad5-c009-4aaf-9715-26d52ff276e8) | ![image](https://github.com/michal-h21/make4ht/assets/7102119/bb4207ec-6e6d-4606-93f7-475de574fdd2) |
|:---:|:---:|
| PDF output | HTML output |

Is this a bug? Is there some alternative environment that I can use instead of tabular to create newlines inside a tikzcd cell that will work with make4ht?

Ivan

**Comment by michal-h21** [comment]
You can also convert the `tikzcd` environment to pictures with this configuration file, `tikz-cd.4ht`:

```latex
% tikz-cd.4ht (2024-01-22-12:04), generated from tex4ht-4ht.tex
% Copyright 2024 TeX Users Group
%
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either
% version 1.3c of this license or (at your option) any
% later version. The latest version of this license is in
%   http://www.latex-project.org/lppl.txt
% and version 1.3c or later is part of all distributions
% of LaTeX version 2005/12/01 or later.
%
% This work has the LPPL maintenance status "maintained".
%
% The Current Maintainer of this work
% is the TeX4ht Project <http://tug.org/tex4ht>.
%
% If you modify this program, changing the
% version identification would be appreciated.
\immediate\write-1{version 2024-01-22-12:04}

\ConfigureEnv{tikzcd}{\Picture+{}}{\EndPicture}{}{}

\Hinput{tikz-cd}
\endinput
```

**Comment by michal-h21** [comment]
@gnull I will add it to the TeX4ht sources. It just seems that I forgot about it  in the past.
