### ISSUE TITLE
Remove anchor tag in xml

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#144]
I use make4ht to convert to docbook. In the resulting xml there are several anchor tags. Is there a way to remove/prevent these tags?   (Some anchor tags are self-closing, and some are open-close pairs)

best regards
hcf

**Comment by michal-h21** [comment]
These anchors are usually created by `\label` or at places, where labels could be used, like in sections or tables. I think the easiest way how to remove them is to create make4ht DOM filter that would remove links that don't link anywhere. 

Can you create a MWE that shows these extra anchors?

**Comment by hcf-n** [comment]
Of course :)

The following minimal example precedes different anchor tags when converting to docbook xml.
````
\documentclass[11pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc,url}
\usepackage{textcomp}
\usepackage[style=authoryear-comp]{biblatex}
\addbibresource{\jobname.bib}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{key,
author = {Author, A.},
year = {2001},
title = {Title},
publisher = {Publisher},
}
\end{filecontents}

\title{Placeholder for title}
\author{Firstname Lastname}
\date{\today}

\begin{document}
\maketitle
\section{Test}
\begin{enumerate}
  \item First item
  \item Second item
\end{enumerate}

Sentence.\footnote{Example footnote.}

Sentence.\footcite{key}

\end{document}
	
````

**Comment by hcf-n** [comment]
Thank you, this works fine!

**Comment by michal-h21** [comment]
Great! So should I close this issue?
