### ISSUE TITLE
make4ht does suppress itemize and enumerate - environments

### ISSUE THREAD

**Issue by MichaelJachan** [michal-h21/make4ht#146]
Dear Author! No matter what options i put, no matter what .cfg file i use, since several months (of updating MiKTeX), the HTML output has changed: 

**The content of itemize-environment is just skipped.** 

If needed, i can give u an MWE lateron. 

Thank you, Michael:)

**Comment by michal-h21** [comment]
Hi Michael, 

this is not expected. I've just tried a small test file with itemize and it was converted without problems. Maybe it is caused by some package you use? I think MWE is necessary for this issue.

**Comment by MichaelJachan** [comment]
Good to hear. I will analyze on my side and tell u later. Thank you:)

**Comment by MichaelJachan** [comment]
Would you give me your MWE?

tex source?
cfg file?
call to htlatex, etc?

Best, MJ:)

**Comment by michal-h21** [comment]
Sure, the following TeX file:

```latex
\documentclass{article}
\begin{document}
Before itemize

\begin{itemize}
  \item first item
  \item second item
\end{itemize}

After itemize
\end{document}
```

compiled using:

      make4ht sample.tex

Should produce this HTML:

```html
<!DOCTYPE html> 
<html lang='en-US' xml:lang='en-US'> 
<head><title></title> 
<meta charset='utf-8' /> 
<meta content='TeX4ht (https://tug.org/tex4ht/)' name='generator' /> 
<meta content='width=device-width,initial-scale=1' name='viewport' /> 
<link href='[sample.css](view-source:file:///home/mint/texexamples/misc/stackexchange/tex4ht/michaeljachan/itemize/sample.css)' rel='stylesheet' type='text/css' /> 
<meta content='sample.tex' name='src' /> 
</head><body>
<!-- l. 3 --><p class='noindent'>Before itemize
</p>
     <ul class='itemize1'>
     <li class='itemize'>first item
     </li>
     <li class='itemize'>second item</li></ul>
<!-- l. 10 --><p class='indent'>   After itemize
</p>
    
</body> 
</html>
```

**Comment by MichaelJachan** [comment]
I found my bug:


WRONG:
make4ht -u -c htmlconfig.cfg %1.tex "xhtml,NoFonts,3,-css" " -cunihtf"


CORRECT:
make4ht -f xhtml -u -c htmlconfig.cfg %1.tex "NoFonts,3,-css" " -cunihtf"


Thank you for your help! :)

**Comment by MichaelJachan** [comment]
It all works. I did something wrong in a sed-based postprocessing of the HTML file. 

Sorry and thank you :)
