### ISSUE TITLE
No support for new lists with enumitem

### ISSUE THREAD

**Issue by rhelder** [michal-h21/make4ht#150]
Here is a MWE:
```
\documentclass{article}

\usepackage{enumitem}
\newlist{duplicate}{enumerate}{2}
\setlist[duplicate,1]{label=\arabic*.}
\setlist[duplicate,2]{label=(\alph*)}

\begin{document}

\begin{enumerate}
    \item item 1
        \begin{enumerate}
            \item subitem 1
            \item subitem 2
            \item subitem 3
        \end{enumerate}
    \item item 2
\end{enumerate}

\begin{duplicate}
    \item item 1
        \begin{duplicate}
            \item subitem 1
            \item subitem 2
            \item subitem 3
        \end{duplicate}
    \item item 2
\end{duplicate}

\end{document}
```

If you run `pdflatex` on the example, you get a pdf with two identical lists. If you run `make4ht` on the example, you get the following output:
```
<!DOCTYPE html> 
<html lang='en-US' xml:lang='en-US'> 
<head><title></title> 
<meta charset='utf-8' /> 
<meta content='TeX4ht (https://tug.org/tex4ht/)' name='generator' /> 
<meta content='width=device-width,initial-scale=1' name='viewport' /> 
<link href='minimal.css' rel='stylesheet' type='text/css' /> 
<meta content='minimal.tex' name='src' /> 
</head><body>
     <dl class='enumerate-enumitem'><dt class='enumerate-enumitem'>
  1. </dt><dd class='enumerate-enumitem'>item 1
         <dl class='enumerate-enumitem'><dt class='enumerate-enumitem'>
      (a) </dt><dd class='enumerate-enumitem'>subitem 1
         </dd><dt class='enumerate-enumitem'>
     (b) </dt><dd class='enumerate-enumitem'>subitem 2
         </dd><dt class='enumerate-enumitem'>
      (c) </dt><dd class='enumerate-enumitem'>subitem 3</dd></dl>
     </dd><dt class='enumerate-enumitem'>
  2. </dt><dd class='enumerate-enumitem'>item 2</dd></dl><p>
  1. item 1
      (a) subitem 1
     (b) subitem 2
      (c) subitem 3
  2. item 2
    
</p></body> 
</html>
```

The result is that the second list is printed just as one line. But the `duplicate` list environment is just a copy of the `enumerate` environment, so the second list should be handled exactly the same as the first. Maybe the `\ConfigureList` command would be of help here, but to me it seems like this should 'just work' – new configuration shouldn't be required for every custom list one defines with `enumitem`.

**Comment by michal-h21** [comment]
In general, `\ConfigureList` is needed for all list items. Without it, output format tags cannot be inserted. But you are right that this could be automatized for Enumitem environments. I've just added support for that to TeX4ht sources. I had to change several files, so it is not practical to send them here, but the changes should appear in few  days in TeX Live.

**Comment by rhelder** [comment]
That's wonderful, thank you! I will be on the lookout for those changes and will test on my end as soon as I see them.
