### ISSUE TITLE
The output directory of pygment seems wrong.

### ISSUE THREAD

**Issue by sakurawald** [michal-h21/make4ht#153]
My source file `fuji.tex` is located in `./processTeX` directory.
I run the command in working directory `./processTex`.
I get the following logs:
```
╰─ make4ht --shell-escape --output-dir /home/sakurawald/Workspace/github/fuji/build/outTeX fuji.tex                                                ─╯
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: fuji.tex
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename     Line    Message
[ERROR]   htlatex: ./chapters/module/afk/afk.tex        29       Package minted Error: Missing Pygments output; \inputminted was
```

The preamble of `fuji.tex` is:
```
% the 'outputdir' is reletive to fuji.tex, and must point the 'output directory' of latex compiler.
\usepackage[outputdir=/home/sakurawald/Workspace/github/fuji/build/outTeX]{minted}
```

The `fuji.pyg` file is expected to occur in `./outTeX` file, and be consumed by latex, but actually not.

Actually, the `fuji.pyg` file is occur in `./processTeX` directory, and not be consumed by the compiler.

![image](https://github.com/user-attachments/assets/4b3df68e-1a43-4c75-8b61-a4bde72a4abc)

The compilation goes and success, the `make4ht` returns 0 and generate the `fuji.html` and `fuji.css` file in `./outputTeX` directory.

The `fuji.html` file looks fine, but the contents about `mined` is blank.

**Comment by michal-h21** [comment]
Do you use up-to-date TeX Live? With the current version of Minted, I get the following error when I try to use the `outputdir` option:

```
! Package minted Error: Package option "outputdir" is no longer needed with min
ted v3+; the output directory is automatically detected for TeX Live 2024+, and
 the environment variable TEXMF_OUTPUT_DIRECTORY can be set manually in other c
ases.
```

**Comment by sakurawald** [comment]
> Do you use up-to-date TeX Live? With the current version of Minted, I get the following error when I try to use the `outputdir` option:
> 
> ```
> ! Package minted Error: Package option "outputdir" is no longer needed with min
> ted v3+; the output directory is automatically detected for TeX Live 2024+, and
>  the environment variable TEXMF_OUTPUT_DIRECTORY can be set manually in other c
> ases.
> ```

It works fine if i using `pdflatex`:
```
        2.times {
            exec {
                workingDir = processTexDir
                commandLine "pdflatex",
                        "-file-line-error",
                        "-interaction=nonstopmode",
                        "-synctex=1",
                        "-output-format=pdf",
                        "-output-directory=${outputTexDir}",
                        "-shell-escape",
                        "fuji.tex"
                println("Compile TeX once.")
            }
        }
```

**Comment by sakurawald** [comment]
The version:
```
╰─ pdflatex                                                                                                                                        ─╯
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
```

**Comment by michal-h21** [comment]
TeX Live included in TeX distributions is often old. Version 3 of Minted was released just a few weeks ago, so it is possible that it is not included in Arch yet. 

You can find the version of Minted in the documentation using:

      $ texdoc minted

On my system, it is: `v3.1.2 from 2024/10/07`.

**Comment by sakurawald** [comment]
> TeX Live included in TeX distributions is often old. Version 3 of Minted was released just a few weeks ago, so it is possible that it is not included in Arch yet.
> 
> You can find the version of Minted in the documentation using:
> 
> ```
>   $ texdoc minted
> ```
> 
> On my system, it is: `v3.1.2 from 2024/10/07`.

Okay, i will check it.
