### ISSUE TITLE
make4ht-tablerows.lua:92: attempt to index a nil value

### ISSUE THREAD

**Issue by Witiko** [michal-h21/make4ht#154]
After PR https://github.com/Witiko/markdown/pull/521, our example make4ht document [`latex-tex4ht.tex`](https://github.com/Witiko/markdown/blob/main/examples/latex-pdftex.tex) fails with the following error:

> ...mf-dist/scripts/make4ht/domfilters/make4ht-tablerows.lua:92: attempt to index a nil value

Here is the full reproducing sequence of commands:

```
$ git clone https://github.com/witiko/markdown.git
$ docker run --rm -it -v "$PWD"/markdown:/workdir -w /workdir/examples ghcr.io/witiko/markdown:3.7.1-35-g0e5c4ccd-latest make latex-tex4ht.html
```

Here is the full output:

```
make4ht --shell-escape latex-tex4ht.tex fn-in
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: latex-tex4ht.tex
...mf-dist/scripts/make4ht/domfilters/make4ht-tablerows.lua:92: attempt to index a nil value
make: *** [Makefile:61: latex-tex4ht.html] Error 1
```

I was unable to pinpoint the exact issue or create a minimal reproducing example yet. Therefore, I temporarily suspended the compilation of the make4ht example in commit https://github.com/Witiko/markdown/pull/521/commits/0e5c4ccd7b3d22fbdb5d31e8695546d625ad3434. I would be happy to revert the commit once this issue has been resolved.

Since the same example document compiles fine with both pdfLaTeX and LuaLaTeX, I assume this crash should be interesting to you regardless of whether this just is something dumb on the part of the Markdown package or not.

**Comment by michal-h21** [comment]
Here is a MWE:

```latex
\documentclass{article}
\usepackage{longtable}
\begin{document}
\begin{tabular}{l l}
  a & b
\end{tabular}

\begin{longtable}{l l}
  a & b\\
\end{longtable}

\ifvmode\IgnorePar\fi\EndP\HCode{<table></table>}
\end{document}
```

**Comment by michal-h21** [comment]
One strange thing is that there must be a table without `class` attribute in your example. I've tried `pipeTables` extension, and it produces normal TeX4ht table structure, so it must be something else that produces such table.

**Comment by Witiko** [comment]
There is a literal table included with `\HCode`.

``` tex
% Besides YAML, LaTeX, and Markdown, you can also type HTML in your documents.
\begin{markdown}
Here is some <b>HTML code</b> mixed *with Markdown*. In `\TeX`{=tex}, the HTML
code will be silently ignored, whereas in `\TeX`{=tex}4ht, the HTML code will
be passed through to the output:

<table border="1">
  <tr>
    <td>Emil</td>
    <td>Tobias</td>
    <td>Linus</td>
  </tr>
  <tr>
    <td>16</td>
    <td>14</td>
    <td>10</td>
  </tr>
</table>
\end{markdown}
```

Perhaps that could be the issue?

**Comment by michal-h21** [comment]
Yes, this will be the issue, because normally, tables generated by TeX4ht have some class for CSS styling. So the quick fix to get the build done would be to use something like `<table class="mdtable" border="1">`. 

It is good that we found this bug so quickly. Fixed version of `make4ht` should appear in TeX Live in few hours, hopefully.

**Comment by michal-h21** [comment]
@Witiko  the updated version of `make4ht` is now in TeX Live, so this issue should be resolved

**Comment by Witiko** [comment]
I can confirm that. Closing here and in https://github.com/Witiko/markdown/pull/523.
