### ISSUE TITLE
Incompatibility with babel-french when using \part and TOC

### ISSUE THREAD

**Issue by Evarin** [michal-h21/make4ht#155]
Hello,

There is a problem when using babel-french, tableofcontents and parts. Here is a minimal example

```latex
\documentclass[11pt]{book}
\usepackage[french]{babel}

\begin{document}

\tableofcontents

\part{Partie 1}

Une Partie

\end{document}
```

Then, `mak4ht minimal` raises many errors and fails to compile:
```
[STATUS]  htlatex:  <- \unskip l.3 ...me{3}{x3-2000\unskip }{QQ2-3-2}{Partie 1}}{5} \relax The control sequence marked <to be read again> should
[ERROR]   htlatex: ./minimal.4ct        ?        Missing \endcsname inserted.
```

After spending days narrowing the error down to babel-french, I found the cause of the problem: a `\unskip` in `babel.ldf`. (line 971) `\DeclareRobustCommand*{\FB@emptypart}{\def\thepart{\unskip}}%`

And figured out a simple solution : adding this line to `french.4ht` :
```latex
\DeclareRobustCommand*{\FB@emptypart}{\def\thepart{}}
```

I have little understanding on how latex works, but I'm happy to have solved my issue, and thought it would be nice to have it fixed in official package (but don't quite understand where the .4ht files are) :)

**Comment by michal-h21** [comment]
Thanks for the report! I've incorporated it into TeX4ht sources, and it seems to work nicely.

**Comment by Evarin** [comment]
Great! There's another more subtle issue: in table of contents (and \refs), parts are not numbered like they should (I. II., etc, that appear properly if you run `pdflatex minimal`). I think that's because of babel-french redefining the `\partname` logic (display "Première Partie" instead of "Part I"), but I can't figure out what's needed to fix that.

**Comment by michal-h21** [comment]
This is actually quite simple, use this version:

```
\DeclareRobustCommand*{\FB@emptypart}{}
```

**Comment by Evarin** [comment]
Oh, indeed, thanks! But then on the part pages it adds it back: "Première Partie I" instead of "Première Partie" (which is why Babel redefined it in the first place)... Still, that's less an inconvenient that having broken refs in my case

**Comment by michal-h21** [comment]
I see. Try to add this to french.4ht:

```
\HAssign\french:part=0
\def\tocpart#1#2#3{\par
  \HAdvance\french:part 1\relax%
  \HCode{<span class="partToc" \a:LRdir>}\uppercase\expandafter{\romannumeral\french:part\relax}\ \  #2\HCode{</span>}\par}%
```
It will use a local counter for parts in TOC. It will use regular numbers,

**Comment by Evarin** [comment]
Thank you, but that fixes the table of contents (when using `\DeclareRobustCommand*{\FB@emptypart}{\def\thepart{}}`), but not the `\ref` (that just appear empty). 

Maybe it would be simpler to redefine the `\part` display handler?

<details><summary>MWE</summary>
<p>The \ref{part} is empty:

```latex
\documentclass[11pt]{book}

\usepackage[french]{babel}
\usepackage{hyperref}

\begin{document}

\tableofcontents
\part{Des arbres - Dans les cours d'école}
\label{part:arbres}

Auprès de mon arbre

\chapter{Bouleau}
\label{chap:bouleau}

Voir partie \ref{part:arbres} 

Chapitre \ref{chap:bouleau}

\end{document}
```
</p>
</details>

**Comment by michal-h21** [comment]
Hmm, I see. So it seems that we should really use `\DeclareRobustCommand*{\FB@emptypart}{}`, so the part number is used in TOC and in references. We can just redefine the configuration that formats the `\part` itself, like with this config file:

```latex
\Preamble{xhtml}
\catcode`\:=11
\Configure{part}{}{}
   {\IgnorePar \EndP\HCode{<h1 class="partHead"\a:LRdir>}%
       \HCode{<span class="titlemark">}\partname
       \HCode{</span><br />}}
   {\HCode{</h1>}\IgnoreIndent\par}
\catcode`\:=12
\begin{document}
\EndPreamble
```

**Comment by Evarin** [comment]
It fixes all my problems, thank you so much! Couldn't it be made the default in `french.4ht`? As that corresponds to the babel-french default it would make sens to have it compatible out-of-the-box.

**Comment by michal-h21** [comment]
I've added all changes to TeX4ht sources, so it should be included in TeX Live update in few days.

**Comment by Evarin** [comment]
Great, thanks for being so reactive!
