### ISSUE TITLE
mathml + mathjax + resizegather leads to Math Input Error

### ISSUE THREAD

**Issue by rkansal47** [michal-h21/make4ht#158]
Hello, first, thank you for this great tool! 

### Issue

mathml + mathjax lead to a `Math Input Error` for equations if the `resizegather` package is imported.

### MWE

```latex
\documentclass[12pt]{report}

\usepackage{resizegather}

\begin{document}

Test $2x = y$.  % this renders fine

\begin{equation}  % this gives an error if resizegather is used
    \label{eq:1}
    2x = y
\end{equation}
 
\end{document}
```

### Command

```bash
make4ht MWE.tex "mathml,mathjax"
```

### Output

<img width="655" alt="Screenshot 2024-12-04 at 12 27 44" src="https://github.com/user-attachments/assets/5386f326-d00e-42ac-a633-94de0d77d2f1">

### Notes

From testing, I found that `mathjax` alone works fine, and also mathml + the `mathjax` v4 beta doesn't give an error on Firefox only (not Safari or Chrome) but still renders weirdly. Also, as shown above, inline equations are rendered fine. Finally, I'll mention that the `resizegather` package is not critical for me so I am able to workaround by simply not importing, but I thought I'd post this in case others have issues (and since this took me a long time to debug)!

**Comment by michal-h21** [comment]
Thanks for the report. It seems that Resizegather isn't really useful in TeX4ht conversion, so I've disabled it in the sources. Your example should work with TeX4ht version from TeX Live soon.
