### ISSUE TITLE
Extension latexmk assumes pdf_mode=0 in latexmkrc

### ISSUE THREAD

**Issue by wojciechmyszka** [michal-h21/make4ht#16]
I am using latexmk for creating all my documents (tex -> pdf conversion). Extension latexmk does not work in this situation. Probably adding -dvi when calling latexmk can solve this problem.

My latexmkrc file (with commented out line $pdf_mode=1 )

[latexmkrc.gz](https://github.com/michal-h21/make4ht/files/2380879/latexmkrc.gz)

**Comment by michal-h21** [comment]
Thanks for the report. I've added the `-dvi` option to the latexmk call, it seems to work on my simple test, I hope it will work on your real life documents as well.

**Comment by wojciechmyszka** [comment]
Thanks for corrections. Works as expected.

I do not know if I should start a new thread. But if (I really do not understand an issue) previous run ends with some kind of error (after successful latexmk run) there is no need to run latexmk again. So it stops. And everything fails (inside make) because of error codes:
```
make4ht -u -f html5+latexmk_build -c mathjax ti03_ulamki_article.tex
Output dir: 	
Compiler: 	latex
Latex options: 	 -jobname=ti03_ulamki_article 
tex4ht.sty :	mathjax,,charset=utf-8
tex4ht	 -cmozhtf -utf8
build_file	ti03_ulamki_article.mk4
Output format	html5
Extension	+latexmk_build
Using build file	ti03_ulamki_article.mk4
setting param correct_exit
setting param ext
setting param ext
Adding: 	ext	dvi
setting param correct_exit
Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Latexmk: All targets (ti03_ulamki_article.dvi ti03_ulamki_article.pdf) are up-to-date
Make4ht: Fatal error. Command latexmk returned exit code 1
Makefile:17: recipe for target 'ti03_ulamki_article.html' failed
make: *** [ti03_ulamki_article.html] Error 1
```

**Comment by michal-h21** [comment]
This is strange issue. Make4ht searches for an error in the log file, specifically for `No pages of output` and `TeX capacity exceeded, sorry`. Doesn't ti03_ulamki_article.log contain these strings?
