### ISSUE TITLE
Table column border extending below table border with pic-tabular

### ISSUE THREAD

**Issue by rkansal47** [michal-h21/make4ht#160]
## Problem

Hello, using `pic-tabular` seems to render tables very well, except for this issue where the column borders are drawn too long if I add a lower border with e.g. `\hline` or `\bottomrule`.

## MWE

```latex
\documentclass[12pt]{report}

\begin{document}

\begin{table}
  \centering
  \begin{tabular}{l|l}
    a & b \\
    \hline
  \end{tabular}
\end{table}

\end{document}
```

## Command

```bash
make4ht mwe.tex  "mathml,mathjax,pic-tabular" 
```

## Output

<img width="133" alt="Screenshot 2024-12-07 at 22 54 34" src="https://github.com/user-attachments/assets/bb35a7ec-a9b7-410e-81f2-92c36b7b6578">

**Comment by michal-h21** [comment]
Thanks for the report. I can confirm this issue, but I cannot figure out why it happens. It seems to persist even if I disable all TeX4ht redefinitions to arrays and tables. So it seems really mysterious. If you don't mind to use an extra command, you can try this variant of `\hline`. It removes vertical space after line, and it seems to work in both PDF and HTML output:

```latex
\documentclass[12pt]{report}

\begin{document}

\makeatletter
\def\lasthline{\noalign{\hrule}\noalign{\vskip-1em\vskip-\arraycolsep}}
\makeatother
\begin{table}
  \centering
  \begin{tabular}{l|l}
    a & b
    \\\lasthline
  \end{tabular}
\end{table}

\end{document}
```

**Comment by rkansal47** [comment]
That worked, thanks for the quick fix as always!
