### ISSUE TITLE
Add --odt-template option to make4ht

### ISSUE THREAD

**Issue by denismaier** [michal-h21/make4ht#17]
Would it be possible to add a command line option `--odt-template` to make4ht. Right now, this is already possible as was demonstrated [here](https://tex.stackexchange.com/questions/464710/use-odt-template-for-make4ht) on TeX.se. I guess it might be useful if this was integrated in make4ht so that it could be used without an additional build file.

**Comment by michal-h21** [comment]
I've added the `odttemplate` extension. It can be used without extension in this way:

      make4ht -um draft -f odt+odttemplate sample.tex "odttemplate=template.odt"

It is not easy to add new command line options to `make4ht`, because they need to provide also short, one letter version and their number is limited (by the alphabet).

**Comment by demai** [comment]
Amazing. This looks great. For me it won't matter if this is an extension or a command line option.

**Comment by michal-h21** [comment]
great, I should make a release to CTAN soon.
