### ISSUE TITLE
Missing spaces in source code listings when using minted

### ISSUE THREAD

**Issue by andreashappe** [michal-h21/make4ht#18]
I am trying to use make4ht to convert my latex lecture notes into html (so that I can create an ebook out of it). The lecture notes contain source code which I have typeset with the minted extension.

While I can create the HTML file, I do have the problem that all minted source code listings are collapsed into a single line. In the HTML source code, each source code line is placed on a new line but no br or similar is added. Is there an easy way of getting newlines into this?

I am using make4ht with the -s option.

**Comment by michal-h21** [comment]
That's strange, I've used Minted in some projects as well and haven't experienced this issue. Can you make a small example that shows this issue?

**Comment by andreashappe** [comment]
I am using the orange book template together with minted with the following configuration:

~~~ latex
  \usepackage{minted}
  \usemintedstyle{tango}
  \setminted{autogobble,breaklines,breakanywhere,fontsize=\footnotesize,frame=single}%,bgcolor=bg}
~~~

And the resulting source code looks like:

~~~ html
<div class="fancyvrb" id="fancyvrb19"><span id="textcolor801"><tspan font-family="ectt" font-size="0900">import</tspan></span><tspan font-family="ectt" fo  nt-size="0900">&#x00A0;</tspan><span id="textcolor802"><tspan font-family="ectt" font-size="0900">os</tspan></span>
  <span id="textcolor807"><tspan font-family="ectt" font-size="0900">domain</tspan></span><tspan font-family="ectt" font-size="0900">&#x00A0;</tspan><span id="  textcolor808"><tspan font-family="ectt" font-size="0900">=</tspan></span><tspan font-family="ectt" font-size="0900">&#x00A0;</tspan><span id="textcolor809"><  tspan font-family="ectt" font-size="0900">user_input</tspan></span><span id="textcolor810"><tspan font-family="ectt" font-size="0900">()</tspan></span>
  <span id="textcolor819"><tspan font-family="ectt" font-size="0900">os</tspan></span><span id="textcolor820"><tspan font-family="ectt" font-size="0900">.</tsp  an></span><span id="textcolor821"><tspan font-family="ectt" font-size="0900">system</tspan></span><span id="textcolor822"><tspan font-family="ectt" font-size  ="0900">(</tspan></span><span id="textcolor823"><tspan font-family="tctt" font-size="0900">'</tspan><tspan font-family="ectt" font-size="0900">ping</tspan><t  span font-family="ectt" font-size="0900">&#x00A0;</tspan><tspan font-family="tctt" font-size="0900">'</tspan></span><tspan font-family="ectt" font-size="0900  ">&#x00A0;</tspan><span id="textcolor824"><tspan font-family="ectt" font-size="0900">+</tspan></span><tspan font-family="ectt" font-size="0900">&#x00A0;</tsp  an><span id="textcolor825"><tspan font-family="ectt" font-size="0900">domain</tspan></span><span id="textcolor826"><tspan font-family="ectt" font-size="0900"  >)</tspan></span>
~~~

**Comment by michal-h21** [comment]
Ah, I see. It seems the `breaklines` option in `\setminted` causes that. I will look at this. In the meantime, you can try the following:

```

\ifdefined\HCode
\setminted{
autogobble,
fontsize=\footnotesize,
frame=single
}%,bgcolor=bg}
\else
\setminted{
autogobble,
breaklines,
breakanywhere,
fontsize=\footnotesize,
frame=single
}%,bgcolor=bg}
\fi
```
Another issue I see are the `<tspan>` elements in the generated code. This can be caused by the default TikZ driver for SVG, it redefines code that `tex4ht` uses for font change commands, so they produce wrong elements. You can try the alternative [TikZ driver](https://github.com/michal-h21/dvisvgm4ht), which shouldn't have these issues. It also produces better images than the default one.

**Comment by andreashappe** [comment]
Hi, that worked! Will try the alternative TikZ driver later on..

Should we keep this ticket open until make4ht works without the workaround?

thank you, Andreas

**Comment by michal-h21** [comment]
I've just updated the `tex4ht` sources with a fix that disables the `breaklines` option. It should be included in TeX Live soon. I think we can close this issue now :)

**Comment by andreashappe** [comment]
thanks for our effort! cheers, Andreas
