### ISSUE TITLE
Linux installation instructions seem incorrect

### ISSUE THREAD

**Issue by PissedCapslock** [michal-h21/make4ht#2]
Perhaps I did something wrong, but I tried to follow the instructions as good as possible. I managed to resolve all problems, but it might be a good idea to update the installation instructions.

Here is what I did

```
cd ~/tools
git clone https://github.com/michal-h21/make4ht.git
cd make4ht
make
```

This resulted in 

```
robins@luanda:~/tools/make4ht()$ make
pandoc -f markdown+definition_lists -t LaTeX CHANGELOG.md > changelog.tex
latexmk -lualatex make4ht-doc.tex
make: latexmk: Command not found
make: *** [make4ht-doc.pdf] Error 127
```

I did not install pandoc. Easy to fix, but might be a good thing to mention this in the installation instructions. I installed `pandoc` using

```
sudo apt-get install pandoc
```

After running `make` again, I now got the following problem

```
robins@luanda:~/tools/make4ht()$ make
latexmk -lualatex make4ht-doc.tex
Latexmk: -lualatex bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
make: *** [make4ht-doc.pdf] Error 10
```

I was able to fix this by adjusting the `Makefile`. I replaced the 

```
latexmk -lualatex make4ht-doc.tex
```

line with

```
lualatex make4ht-doc.tex
```

Now I could run

```
make
sudo make install
```

without problems.

When then running

```
make4ht -e $file_name.mk4 $file_name "3,frames"
```

to process my tex document, I got 

```
/usr/local/bin/make4ht:5: module 'make4ht-lib' not found:
    no field package.preload['make4ht-lib']
    [kpse lua searcher] file not found: 'make4ht-lib'
    [kpse C searcher] file not found: 'make4ht-lib'
```

This was solved by running

```
texhash
```

This was all on an Ubuntu system:

```
robins@luanda:~()$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

with the following version of latex

```
robins@luanda:~()$ latex --version
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
kpathsea version 6.1.1
Copyright 2013 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.2.49; using libpng 1.2.50
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.24.5
```

**Comment by michal-h21** [comment]
Thanks for your report. I updated  the `install.md` file. There are often problems with TeX Live distributed with Linux distros, included packages may be pretty old.

**Comment by Danowsky** [comment]
Trying to install it in a Raspberry Pi. After `make` I get the following error:
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>!
>! fontspec error: "font-not-found"
>! 
>! The font "TeXGyreSchola" cannot be found.
>! 
>! See the fontspec documentation for further information.
>! 
>! For immediate help type H <return>.
>!...............................................  
                                                  
>l.11 \setmainfont{TeX Gyre Schola}

I think it must be a mistake if I have to download a font for using it, right?
