### ISSUE TITLE
Indentation of a line after a line which ends with superscript in algorithm block seems incorrect.

### ISSUE THREAD

**Issue by seunghankang** [michal-h21/make4ht#20]
I tried to transform latex code to html with command line execution `make4ht text.tex`

This is the html result.
![html](https://user-images.githubusercontent.com/49592988/64001337-8750a480-cb42-11e9-83be-4548b1313be2.png)

this is the pdf result.
![pdf](https://user-images.githubusercontent.com/49592988/64001396-ad764480-cb42-11e9-82ea-bcd4ba910c4e.png)

It seems that after superscript ending line, next line indentation goes wrong.
I checked created html, spaces for indentation were different for those lines.
How can I fix it?

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{algorithm}
\usepackage{algpseudocode}

\begin{document}

\begin{algorithm}
  \begin{algorithmic}[0]
    \Procedure{Test Procedure}{}
    \State $x^{100}$
    \State $x+y$
    \State $\omega^{2}$
    \State $a+b$
    \EndProcedure
  \end{algorithmic}
\end{algorithm}

\end{document}
```

**Comment by michal-h21** [comment]
It seems the spurious space is inserted on every odd line, it doesn't depend on the previous lines content. I've fixed that in the `tex4ht` sources, the fix should be included in TeX Live in few days.

Thanks for the report.

**Comment by seunghankang** [comment]
Thank you for quick response!!:smile::smile:

But I am afraid of that superscript may affect the spurious space.
I've tested other case and spurious space is inserted in even line too.
Please see below  case. Thank you.

html result
![html2](https://user-images.githubusercontent.com/49592988/64027846-8a688680-cb7c-11e9-9223-2d8b23cd9eab.png)

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{algorithm}
\usepackage{algpseudocode}

\begin{document}

\begin{algorithm}
  \begin{algorithmic}[0]
    \Procedure{Test Procedure}{}
    \State $x+y$
    \State $x^{100}$
    \State $x/y$
    \State $y=ax+b$
    \State $\omega^{2}$
    \State $E=mc^2$
    \State $F=ma$
    \State $\sigma=E \epsilon$
    \EndProcedure
  \end{algorithmic}
\end{algorithm}

\end{document}
```

**Comment by michal-h21** [comment]
The second test seems to be fixed by the fix as well :)

I hope it will come soon to the TeX distributions. Here is a patch that can be applied to the `html4.4ht` file distributed in TeX Live:

```
--- /usr/local/texlive/2019/texmf-dist/tex/generic/tex4ht/html4.4ht	2019-08-21 23:42:00.000000000 +0200
+++ lit/html4.4ht	2019-08-30 19:43:30.045776575 +0200
@@ -1,4 +1,4 @@
-% html4.4ht (2019-08-20-14:31), generated from tex4ht-html4.tex
+% html4.4ht (2019-08-30-19:43), generated from tex4ht-html4.tex
 % Copyright 2009-2019 TeX Users Group
 % Copyright 1997-2009 Eitan M. Gurari
 %
@@ -17,7 +17,7 @@
 %
 % If you modify this program, changing the
 % version identification would be appreciated.
-\immediate\write-1{version 2019-08-20-14:31}
+\immediate\write-1{version 2019-08-30-19:43}
 
 \exit:ifnot{8859-6,% 
 CJK,% 
@@ -36314,7 +36314,7 @@
     \ifnum \c@ALG@line=10
         \Css{.algorithmic span.label{width:3em; text-align:right;}}\fi
    }
-   {\HCode{</span>&\#xA0;<span\Hnewline class="algorithmic">}%
+   {\HCode{</span>&\#xA0;<span\Hnewline class="algorithmic">}~%
     \special{t4ht@. }}
 \Css{div.algorithmic span.algorithmic{white-space:pre}}
```

**Comment by seunghankang** [comment]
It works well!!
Thank you!!:smile::smile:
