### ISSUE TITLE
build error on ubuntu 18.04

### ISSUE THREAD

**Issue by muralikodali** [michal-h21/make4ht#23]
on ubuntu 18.04 build with make command gives following error :

This is LuaTeX, Version 1.0.4 (TeX Live 2017/Debian) 
 restricted system commands enabled.
LaTeX2e <2017-04-15>
(using write cache: /home/murali/.texlive2017/texmf-var/luatex-cache/generic)(using read cache: /var/lib/texmf/luatex-cache/generic /home/murali/.texlive2017/texmf-var/luatex-cache/generic)
luaotfload | main : initialization completed in 0.173 secondsBabel <3.18> and hyphenation patterns for 1 language(s) loaded.
(./make4ht-doc.tex (/usr/share/texlive/texmf-dist/tex/latex/base/ltxdoc.cls
Document Class: ltxdoc 2017/03/13 v2.0v Standard LaTeX documentation class
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo(load luc: /home/murali
/.texlive2017/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-regular.luc)))
 (/usr/share/texlive/texmf-dist/tex/latex/base/doc.sty(load luc: /home/murali/.
texlive2017/texmf-var/luatex-cache/generic/fonts/otl/lmroman7-regular.luc)
(/usr/share/texlive/texmf-dist/tex/latex/tools/multicol.sty)))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/switch.def)
(/usr/share/texlive/texmf-dist/tex/generic/babel/luababel.def)
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/luababel.def))))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty
(/usr/share/texlive/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua)))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hluatex.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/home/murali/texmf/tex/latex/fontspec/fontspec.sty
(/home/murali/texmf/tex/latex/l3kernel/expl3.sty
(/home/murali/texmf/tex/latex/l3kernel/expl3-code.tex
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty)
! Undefined control sequence.
\__str_escape_x:n #1->\luatex_luaescapestring:D 
                                                {\etex_detokenize:D \exp_aft...

l.14800 ...\c_e_fp          { 2.718 2818 2845 9045 }
                                                  
?

**Comment by michal-h21** [comment]
It seems like a clash between some packages when the documentation is generated. Note that TeX Live 2017 is quite old. Anyway, to skip the documentation build, yu can try the following command: 

     make justinstall

The Lua code used by make4ht should work on older systems.

**Comment by muralikodali** [comment]
make justinstall worked fine. 
thanks for your suggestion.
