### ISSUE TITLE
A possible bug in `dvisvgm_hashes` (maybe due to other things)

### ISSUE THREAD

**Issue by Iey4iej3** [michal-h21/make4ht#26]
[files.zip](https://github.com/michal-h21/make4ht/files/4640276/files.zip)

When I compile `AdicSpaces.tex` with `tex4ebook` along with `dvisvgm_hashes`, there are a lot of warning messages (run with `-a debug`) which look like

```
[INFO]    mkutils: Copy: cp "AdicSpaces-227859f57dad3de81a85d1014109069f.svg" "AdicSpaces-epub/OEBPS"
cp: impossible d'?valuer 'AdicSpaces-227859f57dad3de81a85d1014109069f.svg': Aucun fichier ou dossier de ce type
[INFO]    mkutils: Copy: cp "AdicSpaces-ae94a0fa7735ae8a3ef7651c219e7820.svg" "AdicSpaces-epub/OEBPS"
cp: impossible d'?valuer 'AdicSpaces-ae94a0fa7735ae8a3ef7651c219e7820.svg': Aucun fichier ou dossier de ce type
```

That is, the `svg` files are missing. If I compile it without `dvisvgm_hashes`, the generated `AdicSpaces530x.svg` is empty, but seemingly no warning or error message. In any case, `-a debug` does not stop, and I am unable to extract an MWE, therefore I uploaded the whole TeX source.

**Comment by Iey4iej3** [comment]
Ah, now I see that it is triggered by plain TeX `\overset` command. But why it leads to loss of `svg` files?

**Comment by michal-h21** [comment]
I've modified your macros and was able to cut down the number of missing files to just three. All of them appear in this definition:

```
\begin{defi}
Let $\Ucal$ be an open covering of $X$. Then the covering $\Ucal$ is called \emph{$\Fscr$-acyclic} if the the augmented \v Cech complex
\[
0 \to \Fscr(U) \to \Cvee^0(\Ucal,\Fscr) \to \Cvee^1(\Ucal,\Fscr) \to \Cvee^2(\Ucal,\Fscr) \to \dots
\]
is exact. In other words, the augmentation morphism $\eps$ yields an isomorpism $\Fscr(X) \iso {\Hvee}^{0}(\Ucal,\Fscr)$ and ${\Hvee}^{q}(\Ucal,\Fscr) = 0$ for $q \geq 1$.
\end{defi}
```

What is strange is the fact that it works when I try to extract this code to a standalone file. I will need to investigate it more.

Here are the modified TeX file and package.
[files.zip](https://github.com/michal-h21/make4ht/files/4651004/files.zip)

**Comment by Iey4iej3** [comment]
I forget to mention that after having replace `\overset` by corresponding LaTeX macros, all errors are gone. I uploaded only the modified file:
[mymath.zip](https://github.com/michal-h21/make4ht/files/4657719/mymath.zip)
You can compare it with the original `mymath.sty` in my original `files.zip` (not yours).
Seemingly it has nothing to do with the code you have pasted here. Does it help you find out the reason that happens?

**Comment by michal-h21** [comment]
This error was really random, as I got only three images wrong, all of them from one math environment. The `\overset` command worked in most cases. But if it was fixed by replacing `\overset` with something different, then it is OK. It is just sad that I cannot find the real issue, so it can happen in the future again.

**Comment by Iey4iej3** [comment]
I mentioned that for the original version compiled without `dvisvgm_hashes`, there were no error but `AdicSpaces530x.svg` is empty (seemingly only one file). I want to add that if I pass the generated `.epub` file to `kindlegen`, it will fail.

Compiled with `dvisvgm_hashes`, it is `copy` that generates many `not found` problem like this. I don't understand:
1. Why do we have different number of potential errors with and without `dvisvgm_hashes`?
2. Why are the files expected but not generated?

From a point of view of debugging, it seems better to add a layer of verification, and if an expected file is not generated, an error comes out explicitly (before these `cp` commands), which will help locate the error, and when `tex4ebook` is run with `-a debug`, such an error should stop the program from further processing.

**Comment by michal-h21** [comment]
I've added file exist test to the function that is used for copying of files to the output directory. It doesn't halt the execution, but will produce error message visible even without `-a debug` option. 

I don't honestly know what is the source of this issue, as when I use the code that cause the `dvisvgm` issue in a standalone file, it compiles without issues.
