### ISSUE TITLE
 Package ctex Error: Support package `fontspec' too old.

### ISSUE THREAD

**Issue by wlianghe00** [michal-h21/make4ht#29]
make4ht -x  filename
error:
tex4ht warning: package xeCJK was prevented from loading
)

! Package ctex Error: Support package `fontspec' too old.

run xelatex filename is normal

**Comment by michal-h21** [comment]
Can you please provide a small test file? I am not familiar with the `ctex` package.

**Comment by wlianghe00** [comment]
```\documentclass[10pt]{article}
\usepackage[UTF8]{ctex}
\begin{document}
我是中文 
\end{document}
```

**Comment by michal-h21** [comment]
You can try to add the following option to ctex: `fontset=none`. Preferably only when you compile with `make4ht`:

```
\documentclass[10pt]{article}
\ifdefined\HCode
\usepackage[UTF8,fontset=none]{ctex}
\else
\usepackage[UTF8]{ctex}
\fi
\begin{document}
我是中文 
\end{document}
```

I am able to compile the document with `make4ht -x` then. There are more issues with LuaTeX, but they should be fixable hopefully.

**Comment by michal-h21** [comment]
I've added basic `ctex` support to TeX4ht sources. It now works even with LuaLaTeX.

**Comment by wlianghe00** [comment]
tks.
