### ISSUE TITLE
Error, TeX Gyre Schola font not found.

### ISSUE THREAD

**Issue by dmartzol** [michal-h21/make4ht#3]
Trying to install it in a Raspberry Pi. After `make` I get the following error:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "TeXGyreSchola" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return.
!...............................................  

l.11 \setmainfont{TeX Gyre Schola}
```

I think it must be a mistake if I have to download a font for using it, right?

**Comment by michal-h21** [comment]
Trying to install it in a Raspberry Pi. After make I get the following error:
>
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !
> ! fontspec error: "font-not-found"
> !
> ! The font "TeXGyreSchola" cannot be found.
> !
> ! See the fontspec documentation for further information.
> !
> ! For immediate help type H <return.
> !...............................................
>
> l.11 \setmainfont{TeX Gyre Schola}
>
> I think it must be a mistake if I have to download a font for using it, right?
>
>
This font is used just for typesetting the documentation. It should be
included in TeX distribution, but it might be ommited on RPI. As  a
workaround, try to modify the file make4ht-doc.tex:

replace

\ifdefined\HCode
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\else \usepackage{fontspec}
\setmainfont{TeX Gyre Schola}
\fi

with

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

This will use default fonts and it should compile correctly
