### ISSUE TITLE
make4ht not running

### ISSUE THREAD

**Issue by ishanina** [michal-h21/make4ht#30]
Hi, I'm on mac Catalina, and I am getting errors even just trying to run the command make4ht. The error is

`no field package.preload['make4ht-logging']
`
`	[kpse lua searcher] file not found: 'make4ht-logging'
`
`	[kpse C searcher] file not found: 'make4ht-logging'
`
I'm not sure what I've done wrong, or how to fix it. I installed the latest version of make4ht with Tex Live Utility.

**Comment by michal-h21** [comment]
Hi, I don't have Mac, but I think somebody had similar issue recently. I think I update of TeX Live using `tlmgr update --all` should help.

**Comment by ishanina** [comment]
Thanks for the response. I tried it, but everything is already up to date. I was able to sort of figure out the problem. When I run make4ht from within the make4ht folder, that issue doesn't come up, but when I run it from another folder, it does. Maybe the issue is that the version of make4ht pointed to by $PATH is an alias for the real file? Is there some way to avoid this issue?


Anyways, even when I try to run make4ht on a file (from the folder it is contained in), I still get the following message as output:
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: /Users/ishan/Downloads/bla/Descent.tex
/Library/TeX/texbin/make4ht:67: attempt to index a nil value (local 'formatter')

**Comment by ishanina** [comment]
To clarify the first issue, when I'm in the folder "/usr/local/texlive/2020/texmf-dist/scripts/make4ht", and I run ./make4ht, I don't get the no field package.preload['make4ht-logging'] problem.

When I'm in any other folder, for example the parent folder /usr/local/texlive/2020/texmf-dist/scripts, and i run ./make4ht/make4ht, I get the error.

**Comment by michal-h21** [comment]
Isn't it possible that you have multiple `make4ht` versions on your computer? I think you may have an older version somewhere in `/Library/TeX`.

**Comment by ishanina** [comment]
I had a version in the 2019 folder of TexLive, which I have now removed, but I don't think that is the problem, and removing it hasn't fixed anything.

The strange thing is that just running the binary make4ht file gives different results depending on if I run it from the make4ht folder or elsewhere. I even tried downloading a copy of make4ht directly from this repo, and I get the same issue for that.

**Comment by ishanina** [comment]
Is there something about make4ht that calls files relative to the working directory? That seems to be the issue.

**Comment by michal-h21** [comment]
No, it uses the KPSE mechanism that TeX itself uses. If you have a local version of installation somewhere in your local TEXMF, it will always use these first, instead of the version distributed in TeX Live.

Can you run it with the `-a debug` option and pass the output here?

What does the following commands say? :

     kpsewhich mkutils.lua
     kpsewhich make4ht-logging.lua

**Comment by ishanina** [comment]
I get the same results with the -a debug option when I am not in the make4ht folder: 
```
(base) ishans-mbp:bla ishan$ make4ht -a debug
/Library/TeX/texbin/make4ht:7: module 'make4ht-logging' not found:
	no field package.preload['make4ht-logging']
	[kpse lua searcher] file not found: 'make4ht-logging'
	[kpse C searcher] file not found: 'make4ht-logging'

```
The other commands give nothing
```
(base) ishans-mbp:bla ishan$ kpsewhich mkutils.lua
(base) ishans-mbp:bla ishan$ kpsewhich make4ht-logging.lua

```

**Comment by michal-h21** [comment]
@ishanina it is strange that `kpswhich` cannot find these files, it seems like something is broken in your TeX distribution. Can you find them in `/usr/local/texlive/2020/texmf-dist/scripts/make4ht`? If yes, you can try to fix your TeX Live using the `mktexlsr` command. And maybe `tlmgr update --all`.

**Comment by ishanina** [comment]
@michal-h21 I think you are right that something is wrong in my TeX distribution. I was able to fix the issue by switching to MiKTeX (even reinstalling TeXLive didn't work). Anyways, thanks so much!
