### ISSUE TITLE
mathjax extensions

### ISSUE THREAD

**Issue by ishanina** [michal-h21/make4ht#33]
Hi,

I was wondering if there is a way to load mathjax extensions in the make4ht output.

Right now, running make4ht with mathjax configured gives the following output to configure mathjax:
```
 <script> window.MathJax = { tex: { tags: "ams", inlineMath: [ ["\\\(","\\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true, processEnvironments: true, packages: ['base', 'color', 'ams'] }, loader: { load: ['[tex]/color', '[tex]/ams']] } }; </script> 
 <script type="text/javascript" async="async" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>  
```

The output I would like is:

```
 <script> window.MathJax = { tex: { tags: "ams", inlineMath: [ ["\\\(","\\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true, processEnvironments: true, packages: ['base', 'color', 'ams', 'newcommand'] }, loader: { load: ['[tex]/color', '[tex]/ams', '[tex]/newcommand']] } }; </script> 
 <script type="text/javascript" async="async" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>  
```
Here I have loaded the 'newcommand' extension for mathjax in addition to the others. As of now, my solution is that I simply post-process the html with a script to manually add in the extension, but it would be nice if there was a way to do this from within make4ht.

Thanks!

**Comment by michal-h21** [comment]
Hi, you can try this: [work-in progress documentation](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#x8-680007.19.3). I am not sure if it still works, because there was a new MathJax release since I wrote this, but I hope it does.

**Comment by ishanina** [comment]
Thanks for the response. When I put in the code from the documentation, it adds in an additional line configuring Mathjax, giving an output like this:

```
 <script> window.MathJax = { tex: { tags: "ams", inlineMath: [ ["\\\(","\\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true, processEnvironments: true, packages: ['base', 'color', 'ams'] }, loader: { load: ['[tex]/color', '[tex]/ams'] } }; </script> 
 <script type="text/javascript" async="async" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>  
 <script> window.MathJax = { tex: { macros: {  sc: "\\small\\rm", sl: "\\it",  } } }; </script> </head><body 

```
 It would be great if instead it modified the already existing line. Is there any way to do this?

**Comment by michal-h21** [comment]
I've updated TeX4ht sources, so in the next TeX Live update it should be possible to use something like this:

```
\Preamble{xhtml}
\Configure{MathJaxConfig}{{
    tex: {
      tags: "ams",
      \detokenize{%
      inlineMath: [ ["\\\(","\\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],}
      processEscapes: true,
      processEnvironments: true,
      macros: {
        sc: "\\small\\rm",
        sl: "\\it",
      }
      packages: ['base', 'color', 'ams']
  },
  loader: {
    load: ['[tex]/color', '[tex]/ams']
  }
};
}
\begin{document}
\EndPreamble
```

**Comment by ishanina** [comment]
Excellent, I got the update and it works perfectly!

Thanks again
