### ISSUE TITLE
MathJax output is not generated

### ISSUE THREAD

**Issue by scimax** [michal-h21/make4ht#37]
Hi,

I'm trying to use `make4ht` with MathJax code being generated instead of png images for formulas. After succesfully installing `make4ht` (`make4ht version v0.3e`) and running the code with my `.tex` file, it works nicely with formulas as pngs. So following the edit of the [stackexchange answer regarding this question](https://tex.stackexchange.com/a/402159), I thought it would be sufficient to simply run
```sh
 make4ht -f html5+mathjaxnode -d html MyTexFile.tex
```
(I also exported the result to a subfolder `html`). Quickly I realized that I'm missing the package [mathjax-node-page](https://github.com/pkra/mathjax-node-page/) so after installing it the above command did not complain anymore with `'mjpage' is not recognized as an internal or external command,`. Also, the output folder included now an empty file called `mathjax-chtml.css`. But the pngs were still generated and the main html file included those instead of a mathjax code.

What am I doing wrong here? Do I have to consider the stack exchange answer before the edit, including the `mathnode.lua` file?

My system is:
- Windows 10 OS
- pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7250 64-bit)
- node 5.6.0 (a little bit old, but could this be the reason? I'm not using node very often)
- I'm also using [PythonTex](https://github.com/gpoore/pythontex/) but this is ran in advance anyways so it should not interfer, isn't it?
- Currently, I'm testing the `make4ht' command from the `git bash`, but, once fully operational, I would like to embed it in the Build command in Texstudio.

**Comment by michal-h21** [comment]
The `mathjaxnode` extension needs MathML output. It isn't requested by default, so you need to pass the `mathml` option, like this:

     make4ht -f html5+mathjaxnode -d html MyTexFile.tex "mathml"

I've just updated make4ht sources to require this option by default, so you can ommit it if you install the development version.

**Comment by scimax** [comment]
Thanks a lot! It works now! There was another error thrown by make4ht. But after debugging my code I figured it out. Just a minor mistake in latex: `\phi_{\textbf{offset}}` which works in pdftex. But I had to change it to `\phi_{\text{offset}}`, and, in fact, that's what I aimed for originally.

**Comment by michal-h21** [comment]
@scimax I think `\textbf` should work in up-to-date TeX4ht. I've fixed this issue last week.
