### ISSUE TITLE
Feature request: option to return non-zero exit code on any error

### ISSUE THREAD

**Issue by ldr709** [michal-h21/make4ht#39]
When running `make4ht` inside a makefile, it is often useful for `make` to be able to know whether the compilation had errors. While this can be done by parsing the log, and a similar effect can accidentally be achieved by `settings.interaction = "errorstopmode"` and piping in `/dev/null`, these are kind of ugly workarounds.

**Comment by michal-h21** [comment]
This is a good idea. I've added this feature, utilizing the built-in logging mechanism. It sets the error status for error and fatal messages. It doesn't set the exit code in the interactive mode (`-a debug` option), because log parsing isn't active in this case.
