### ISSUE TITLE
conditional string compare using ifnum and \pdfstrcmp / \strcmp

### ISSUE THREAD

**Issue by neerajky** [michal-h21/make4ht#4]
sample.tex:
\documentclass{article}
\usepackage{alternative4ht}
\usepackage{makeidx}
\usepackage{multirow}
\altusepackage{fontspec}
\altusepackage{xeCJK}
\altusepackage{xunicode}
\setCJKmainfont{AozoraMinchoRegular}
\defaultfontfeatures{Mapping=tex-text} % To support LaTeX quoting style
\defaultfontfeatures{Ligatures=TeX}
\pagenumbering{roman}
\providecommand{\tabularnewline}{\}

\ifnum\pdfstrcmp{AA}{AA}=0
   \newcommand{\documentname}{マニAA}
\else\ifnum\pdfstrcmp{BB}{BBC}=0
    \newcommand{\documentname}{マニBB}
\fi\fi

\title{TestHTML}
\date{\mydate{\today}}
\begin{document}
\clearpage
% -------- sections ----------------
\pagenumbering{arabic}
\setcounter{page}{1}

% end preamble
% Chapters
%\documentname
この章では、コマンドラインインターフェースで使用可能な機能について解説します。ユーザが使用できるオプションについて知り>たい場合は本章>を参照してください。
This section is in english.
\end{document}

Compile Command:
 make4ht -ul sample.tex

Error:
alternative4ht: no patch file for xunicode
! Undefined control sequence.
l.14 \ifnum\pdfstrcmp
                   {AA}{AA}=0
? 

Issue:
htlatex can parse \ifnum\pdfstrcmp but make4ht can't.
is this an issue or an expected behaviour?

**Comment by neerajky** [comment]
package included:
\usepackage{xstring}

change in conditional check:
\IfStrEq{AA}{AA}{
   \newcommand{\documentname}{マニAA}
}{
   \newcommand{\documentname}{マニBB}
}

Workaround: change the conditional check in tex file and its working with make4ht.

**Comment by michal-h21** [comment]
Sorry for a late reply, I had some health issues and wasn't really
productive past month.

The issue here is that `\pdfstrcmp` command  isn't available in LuaTeX
by default, but you can fix that easily. Add this code to your
preamble before you use `pdfstrcmp`:

    \usepackage{ifluatex}
    \ifluatex
    \usepackage{pdftexcmds}
    \makeatletter
    \let\pdfstrcmp\pdf@strcmp
    \makeatother
    \fi

Best ragards,
Michal
