### ISSUE TITLE
Incompatibility between subfiles package v2.2 and make4ht v0.3f 

### ISSUE THREAD

**Issue by gsalzer** [michal-h21/make4ht#40]
Consider the two files
```
% main.tex
\documentclass{article}
\usepackage{subfiles}
\begin{document}
\subfile{sub}
Kilroy was here.
\end{document}

% sub.tex
\documentclass[main]{subfiles}
\begin{document}
\end{document}
```
`latex main` processes without errors and produces a document with the text `Kilroy was here.`
`make4ht main` generates an empty html file. `main.log` ends with the error message
```
(\end occurred inside a group at level 1)

### semi simple group (level 1) entered at line 4 (\begingroup)
### bottom level 
```
which is caused by `\end{document}` in `sub.tex`.

I'm the maintainer of the `subfiles` package, and the issue was reported for this package (see https://github.com/gsalzer/subfiles/issues/20). Apparently, `make4ht` modifies `\end`, which interferes with the silencing of `\end{document}` by the `subfiles` package.
I don't yet understand the issue fully, so I can't tell whether the issue can be fixed, and on which side. It may be related to the new handling of `\end` macros in the current LaTeX release.

Version info: `main.log` starts with
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex 2020.12.9)
...
) (/usr/local/texlive/2020/texmf-dist/tex/generic/tex4ht/tex4ht.sty
version 2020-10-16-13:47
...
) (/usr/local/texlive/2020/texmf-dist/tex/generic/tex4ht/usepackage.4ht
version 2020-10-17-13:53
) (/usr/local/texlive/2020/texmf-dist/tex/latex/subfiles/subfiles.sty
Package: subfiles 2020/11/14 v2.2 Multi-file projects (package)
```

**Comment by michal-h21** [comment]
@gsalzer thanks for the report. The problem is that `\end{document}` command in `sub.tex` executes `enddocument` hook that TeX4ht uses to finish the document processing. It doesn't process any content after this point. 

The following code works with TeX4ht:

```
\def\subfiles@renewEndDocument#1{%
  \ifcsname subfiles@end\endcsname
  \else
    \subfiles@saveEndTo\subfiles@end
  \fi
  \let\enddocument\begingroup
  \expandafter\def\csname end \endcsname##1{%
    \romannumeral
    \subfiles@StrIfEqTF{##1}{document}{%
      \z@
      \subfiles@restoreEndFrom\subfiles@end
      #1%
    }{%
      \expandafter\expandafter\expandafter\z@\subfiles@end{##1}%
    }%
  }%
}
```
I've added just the   `\let\enddocument\begingroup` to prevent hooks from being executed. `\begingroup` is used because I got extra `\endgroup` error otherwise.

**Comment by gsalzer** [comment]
Hmm, this doesn't look like a sound fix. I'm redefining `\end ` (note the trailing space) exactly to avoid executing any hooks, but you disable the code be redefining `\end` (no trailing space). Logically, it is up to the `subfiles` package to hide certain `\begin`/`\end{document}` commands together with the hooks, because TeXnically, the code isn't there. How does `make4ht` decide which `\begin`/`\end{document}`s to process?

**Comment by gsalzer** [comment]
What is a reliable way to detect that the code is executed in the context of `make4ht`? Is there any macro that will be defined in this situation?

**Comment by michal-h21** [comment]
@gsalzer `make4ht` loads `tex4ht.sty` package. It is possible to test for it's presence using `\ifdefined\HCode ... \fi`, for example. TeX4ht can also patch commands defined by any package, so I can add the macro above to such patch. It won't be necessary to change anything in `subfiles.sty` in such case. The downside is that it such patch on TeX4ht side may break if the `subfiles` macros change in the future.

The patch file, `subfiles.4ht` can look like this:

```
% redefine \subfiles@renewEndDocument to prevent TeX4ht issues
\def\:tempa#1{%
\let\enddocument\begingroup% don't stop document processing in the included subfile
\o:subfiles@renewEndDocument:{#1}% call original macro
}
% Tex4ht's version of \let. it saves original command as \o:cmdname:
\HLet\subfiles@renewEndDocument\:tempa

\Hinput{subfiles}
\endinput

```

This seems to process the document correctly. 

I've found that hooks aren't indeed executed at the the sub-document's `\end{document}`, but TeX4ht still stops the processing here. I cannot figure out why.

**Comment by gsalzer** [comment]
I will try to use a double strategy: redefining `\enddocument` (which is normally useless since I skip its execution when redefining `\end `) *and* redefining `\end ` at the same time. This could also increase the compatibility with old LaTeX versions which didn't have `\end ` (with space) and the additional hooks.
Redefining the internal macros of `subfiles` is indeed not stable since I have rewritten the code several times since I took over the package, in order to remove conflicts with other packages.

**Comment by michal-h21** [comment]
@gsalzer sounds great!

**Comment by llorracc** [comment]
Thanks for the incredibly quick reply!  So, to make sure I understand, you're saying make4ht looks for cfg and mk4 AND for 4ht files in the directory of the target document?  

PS.  I confirmed that (somewhat painfully) upon reverting to TeXlive 2020 the problem goes away.  That would seem to confirm @gsalzer's guess (and your followup) that the problem stemmed from some change introduced in TeXLive 2021.

**Comment by michal-h21** [comment]
@llorracc `.4ht` files use the same mechanism for lookup as LaTeX itself, so they can be placed in the document directory, or in the TEXMF tree. You can even put them in a local TEXMF tree, like `~/texmf/tex/latex/tex4ht/subfiles.4ht`, if you are on Linux. This way the file would be available for TeX files in any directory. The downside is that this location takes precedence over TeX Live, so if I update TeX Live with a new version, your local version would still be used.

**Comment by LottaIn** [comment]
I have a similar problem. I've used text4ht for years, but after the last MikTex update it doesn't generate html files at all. Even the simplest code, with no additional packages:

```
\documentclass[a5paper, twoside, 11pt, openany]{book}
\begin{document}
test text
\end{document}
```
results in the message: 

`" Extra \endgroup. <recently read> \endgroup"`


How to fix it?

**Comment by michal-h21** [comment]
@LottaIn your sample file compiles fine with TeX Live. Could you run `make4ht -a debug filename.tex` and post the full output here?

I guess that TeX4ht files in Miktex are too old and updates to LaTeX core broke them.

**Comment by LottaIn** [comment]
Thanks for immediate feedback. The whole output:
```

[INFO]    mkparams: Output dir:
[INFO]    mkparams: Compiler: latex
[INFO]    mkparams: Latex options: -jobname=test
[INFO]    mkparams: tex4ht.sty: xhtml,,charset=utf-8
[INFO]    mkparams: tex4ht:  -cmozhtf -utf8
[INFO]    mkparams: build_file: test.mk4
[INFO]    mkparams: Output format: html5
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: test.tex
[INFO]    mkutils: Load extension       common_domfilters
[INFO]    mkutils: Cannot open config file      test.mk4
[INFO]    make4ht-lib: setting param correct_exit
[INFO]    make4ht-lib: setting param correct_exit
[INFO]    make4ht-lib: setting param correct_exit
[INFO]    make4ht-lib: setting param ext
[INFO]    make4ht-lib: Adding:  ext     dvi
[WARNING] tocid: char-def module not found
[WARNING] tocid: cannot fix section id's
[INFO]    htlatex: LaTeX call: latex --interaction=errorstopmode -jobname=test   \makeatletter\def\HCode{\futurelet\HCode\HChar}\def\HChar{\ifx"\HCode\def\HCode"##1"{\Link##1}\expandafter\HCode\else\expandafter\Link\fi}\def\Link#1.a.b.c.{\g@addto@macro\@documentclasshook{\RequirePackage[#1,html]{tex4ht}}\let\HCode\documentstyle\def\documentstyle{\let\documentstyle\HCode\expandafter\def\csname tex4ht\endcsname{#1,html}\def\HCode####1{\documentstyle[tex4ht,}\@ifnextchar[{\HCode}{\documentstyle[tex4ht]}}}\makeatother\HCode xhtml,,charset=utf-8,html5.a.b.c.\input "\detokenize{test.tex}"
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.8 32-bit Portable)
entering extended mode
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-08-27> (test.tex
(c:\miktex\texmfs\install\tex/latex/base\book.cls
Document Class: book 2021/02/12 v1.4n Standard LaTeX document class
(c:\miktex\texmfs\install\tex/latex/base\bk11.clo))
(c:\miktex\texmfs\install\tex/latex/tex4ht\tex4ht.sty)
! Extra \endgroup.
<recently read> \endgroup

l.3 \begin{document}

?
```

**Comment by u-fischer** [comment]
@LottaIn Such problems seldom depend on the pdftex version, but the versions of the styles are relevant.  

Open `c:\miktex\texmfs\install\tex/latex/tex4ht\tex4ht.sty` and check its date. I suspect that it is outdated---I can reproduce your error if I copy a tex4ht.sty from a texlive 2019 in my folder.

**Comment by LottaIn** [comment]
> Open `c:\miktex\texmfs\install\tex/latex/tex4ht\tex4ht.sty` and check its date. I suspect that it is outdated---I can reproduce your error if I copy a tex4ht.sty from a texlive 2019 in my folder.

version 2008-10-27-17:23

**Comment by michal-h21** [comment]
@LottaIn it is really old. I've tried to update Miktex on one computer in my work and it is from 2021-03-06, which is quite old too. The current version of `tex4ht.sty` in TeX Live is from 2021-09.14. As you use current LaTeX kernel, you need the recent `tex4ht.sty` that supports it.

**Comment by u-fischer** [comment]
2008 is old ;-). I have in a current miktex `tex4ht.sty (2021-03-06-13:30)`. But my tex4ht.sty is in tex/generic/tex4ht. Try to what happens if you (re)move the `tex/latex/tex4ht` folder.

**Comment by LottaIn** [comment]
> 2008 is old ;-). I have in a current miktex `tex4ht.sty (2021-03-06-13:30)`. But my `tex4ht.sty` is in `tex/generic/tex4ht`. Try what happens if you (re)move the `tex/latex/tex4ht` folder.

@michal-h21 @u-fischer 
I found another tex4ht.sty file in `tex/generic/tex4ht` and it's version is 2021-03-06-13:30.  I changed the name of the folder containing the older version and now it works. Thanks!
