### ISSUE TITLE
mathjax-node-page has been retired

### ISSUE THREAD

**Issue by pkra** [michal-h21/make4ht#41]
Just FYI. I retired mathjax-node-page since MathJax v3 works in nodejs directly (see https://github.com/mathjax/MathJax-demos-node for some examples).

**Comment by michal-h21** [comment]
@pkra thanks for the pointer. Is some replacement for the `mjpage` command available in the node installation of MathJax?

**Comment by pkra** [comment]
Not directly but they are found in the link I posted.

**Comment by michal-h21** [comment]
OK, thanks, I will try to incorporate some version of `mml2chtml-page`. Is there any practical difference between examples in the `direct` directory and in the `component` directory? For example in speed or in size of the converted documents.

**Comment by pkra** [comment]
I don't use those examples myself, I'm afraid. You might try asking the MathJax team.

**Comment by michal-h21** [comment]
I've created a new project, based on the demos. It supports both LaTeX and MathML: https://github.com/michal-h21/mjcli

Now I need to create a new `make4ht` extension to handle this command.

**Comment by michal-h21** [comment]
I've created new make4ht extension, `mjcli`. It uses the [mjcli](https://github.com/michal-h21/mjcli) command for the conversion. Unlike the older `mathjaxnode` extension, it supports both MathML and LaTeX math. It uses CHTML by default, but it supports also SVG.

It can be required using 

     make4ht -f html5+mjcli filename.tex

for the MathML input or 

     make4ht -f html5+mjcli filename.tex "mathjax" 

for LaTeX math input. 

It extracts MathJax CSS from the generated files and joins them into one CSS file, which results in some file size savings.
