### ISSUE TITLE
extraneous mathjax configuration

### ISSUE THREAD

**Issue by pkra** [michal-h21/make4ht#42]
This is more of an observation. The mathjax option creates the following output (for me using v0.3f):

```html
<script>window.MathJax = { tex: { tags: "ams", inlineMath: [ ["\\\(","\\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true, processEnvironments: true, packages: ['base', 'color', 'ams'] }, loader: { load: ['[tex]/color', '[tex]/ams'] } }; </script> 
<script src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js' id='MathJax-script' async='async' type='text/javascript'></script>
```

The first script seems somewhat odd since it doesn't really do anything. For example, 

* since the second script loads a "-full" component, the TeX input extensions don't have to be specified. 
* inlineMath has a third backslash
* displayMath delimiters are the standard ones
* escapeProcess, pocessEnvironments match the MathJax's defaults
* tags:ams seem odd as default but without automatically wrapping `\ref` (or perhaps `\eqref`) in delimiters, this doesn't really help users.

**Comment by michal-h21** [comment]
Thanks for your comment. I think various options accumulated thanks for the user requests and bug reports. So yo think most of this should be removed? Probably except of inlineMath, which seems to be necessary to support `\( ...  \)` which is used by TeX4ht MathJax support by default. It seems to work even with three backslashes, but I will fix that of course.

**Comment by pkra** [comment]
Thanks for your response.

> I think various options accumulated thanks for the user requests and bug reports. 

Makes perfect sense.

> So yo think most of this should be removed? 

I think all of it can be removed (at least as default output). I don't know how customizable things are (I don't have that much [recent] experience with make4ht/tex4ht). E.g., tags: ams could make sense if the TeX file uses amsmath. But as I wrote users would still need to wrap \ref's to equations in math mode to get MathJax to fix them. 

> Probably except of inlineMath, which seems to be necessary to support \( ... \) which is used by TeX4ht MathJax support by default.

[MathJax's TeX input defaults to \( \)](http://docs.mathjax.org/en/latest/options/input/tex.html) so you don't need it (and I suspect that's why it works right now).

I also noticed anothre problem duee to the packages part of the configuration - it currently prevents others packages from working. E.g., I just ran into an issue with a document using a "poor man's preamble", i..e, adding some \newcommand's to the HTML. The newcommand extension won't be activated with the current configuration since it overrides the -full component's setup. I'm not sure if that was an intentional "blocking" of packages included in the -full component.

**Comment by michal-h21** [comment]
> I think all of it can be removed (at least as default output). I don't know how customizable things are (I don't have that much [recent] experience with make4ht/tex4ht). E.g., tags: ams could make sense if the TeX file uses amsmath. But as I wrote users would still need to wrap \ref's to equations in math mode to get MathJax to fix them.

It can be [configured](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#x8-770007.19.3), luckily. References are bit harder. [Here are some tips](https://tex.stackexchange.com/a/378359/2891) how to handle them (maybe it is a bit outdated too, it is from 2017).

> MathJax's TeX input defaults to ( ) so you don't need it (and I suspect that's why it works right now).
> 
> I also noticed another problem due to the packages part of the configuration - it currently prevents others packages from working. E.g., I just ran into an issue with a document using a "poor man's preamble", i..e, adding some \newcommand's to the HTML. The newcommand extension won't be activated with the current configuration since it overrides the -full component's setup. I'm not sure if that was an intentional "blocking" of packages included in the -full component.

That's good to know. So I will remove most of it, maybe except `tags: ams`. Thanks again for this report.

**Comment by pkra** [comment]
> It can be configured, luckily. References are bit harder. Here are some tips how to handle them (maybe it is a bit outdated too, it is from 2017).

Thanks for the pointers - the user configurability is really great, generally speaking. (I was actually thinking more about make4ht/tex4ht automatically generating different configurations, depending on the TeX input. But it's not important.)

Thank you again for your kind responses and consideration.

**Comment by michal-h21** [comment]
> Thanks for the pointers - the user configurability is really great, generally speaking. (I was actually thinking more about make4ht/tex4ht automatically generating different configurations, depending on the TeX input. But it's not important.)

TeX4ht is highly configurable, but it is not always easy. Work on the better documentation is slow, unfortunately.

**Comment by michal-h21** [comment]
I've updated TeX4ht sources, so it should be fixed in TeX Live soon.
