### ISSUE TITLE
Problem after \maketitle in conversion to docbook

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#44]
When converted to docbook, the following MWE treats the footnote as a paragraph.
```
\documentclass[a4paper,12pt]{article}
\usepackage[T1]{fontenc}                         
\usepackage[utf8]{inputenc}                       
\title{Placeholder title}
\begin{document}
\maketitle 
Test sentence.\footnote{Test.}
\end{document}
```
Normal behavior of the footnote is restored when \maketitle is followed by a blank line or \section{} i.e.
```
\documentclass[a4paper,12pt]{article}
\usepackage[T1]{fontenc}                         
\usepackage[utf8]{inputenc}                       
\title{Placeholder title}
\begin{document}
\maketitle 

Test sentence.\footnote{Test.}
\end{document}
```

**Comment by michal-h21** [comment]
@hcf-n  you are right. New paragraph should be started after `\maketitle`. Try the following `.cfg` file:

```
\Preamble{xhtml}
\Configure{maketitle}
   {\HCode{<info role="maketitle">}}
   {\HCode{</info>}\par\ShowPar}
   {\HCode{<title>}}{\HCode{</title>}}
\begin{document}
\EndPreamble
```

I've fixed it in TeX4ht sources, so it should be available in TeX Live soon.

**Comment by hcf-n** [comment]
With the MWE with an extra line I also get tre unwanted blank spaces before the text in the first paragraph
`-><para>   Test sentence.<anchor xml:id="x1-2f1"/><footnote><para>Test.</para`

**Comment by michal-h21** [comment]
Try this build file:

```
local domfilter = require "make4ht-domfilter"

local process = domfilter {
  function(dom)
    for _,para in ipairs(dom:query_selector("para")) do
      local children = para:get_children()
      if #children > 0 then
        local first = children[1]
        if first:is_text() then
           first._text = first._text:gsub("^%s*", "")
        end
      end

    end
    return dom
  end
}

Make:match("xml$", process)
```

**Comment by hcf-n** [comment]
Yes, that removes the three additional spaces.

**Comment by michal-h21** [comment]
Great. This issue is unfortunatelly quite hard to fix on the TeX side, as spaces are inserted to the DVI file at various places and it is almost impossible to catch them all.
