### ISSUE TITLE
Strange footnotes in docbook with memoir

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#45]
The following MWE gives to strange footnotes when converting to docbook whith memoir

```
\documentclass[a4paper,12pt,article]{memoir}
\usepackage[T1]{fontenc}                         
\usepackage[utf8]{inputenc}                       
\title{Placeholder title}
\begin{document}
\maketitle 

Test sentence.\footnote{Test.}
\end{document}
```

The footnote in docbook looks like:
`footnote><para><inlineequation><inlinemediaobject><imageobject><imagedata fileref="Praktikumssjangeren1x.png"/></imageobject></inlinemediaobject></inlineequation>Test.</para></footnote>`

**Comment by michal-h21** [comment]
Try this configuration file:

```
\Preamble{xhtml}
\catcode`\:=11
\Configure{footnotetext}
    {\HCode{<footnote><para>}\setbox\tmp:bx=\hbox\bgroup\let\@makefnmark\relax}
    {\egroup}%
    {\HCode{</para></footnote>}}
\catcode`\:=12
\begin{document}
\EndPreamble

```

**Comment by hcf-n** [comment]
Works fine! Will it be included in the source?

**Comment by michal-h21** [comment]
Yes, I've added it to the sources. I've also added `\textuperscript` and `\textsubscript` support.
