### ISSUE TITLE
Document language in odt

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#46]
Odt documents seems to miss information on document language. Language set in babel should also be set in meta.xml. When babel is set to 'norsk', I think meta.xml should contain something along the lines of:
`<dc:language>nb-NO</dc:language>`

MWE:
```
\documentclass[11pt, a4paper]{article}
\usepackage[norsk]{babel}
\usepackage{fontspec}
\begin{document}
\title{Tittel}
\author{Ola Normann}
\date{\today}
\maketitle
\section{Overskrift}
Setning.\footnote{Footnote.}
\end{document}
```

**Comment by michal-h21** [comment]
You can add stuff to `meta.xml` using `\Configure{META}`:

```
\Preamble{xhtml}
\Configure{META}{<dc:language>nb-NO</dc:language>\Hnewline}
\begin{document}
\EndPreamble
```

The validator doesn't have an issue with that, but LO still doesn't switch to the correct language for spell checking, so it is possible that some other configurations are needed.
