### ISSUE TITLE
./make4ht-lib.lua:5: attempt to index global 'logging' (a nil value)

### ISSUE THREAD

**Issue by jsbien** [michal-h21/make4ht#47]
The message is from the fresh install from the repository on Debian buster. The version from the Debian package produced the error I encountered already some time ago: https://tug.org/pipermail/xetex/2019-March/027455.html. The discussion at  https://tex.stackexchange.com/questions/225783/install-make4ht-with-miktex made me try `texlua make4ht ...`, it also complaines about \bbl@loaded being an undefined sentence. An experiment on Debian testing gives some othe Lua-related errors.
Fortunately I have no specific deadline for making the conversion, so I can "make haste slowly".

**Comment by michal-h21** [comment]
Hello Janusz, this is strange, because the `logging` library is part of `make4ht` for more than a year. I think there was some issue with initial release of TeX Live 2020, but they were fixed quickly. Could you run `make4ht` with the `-a debug` option and post the terrminal output here? I hope it will tell us something.

**Comment by jsbien** [comment]
make4ht installed locally:
`jsbien@JSBbuster:~/work/make4ht$ which make4ht`
`/home/jsbien/.local/bin/make4ht`
The debug option doesn't provide any additional information:
`jsbien@JSBbuster:~/work/make4ht$ make4ht -a debug -uxc hej.cfg -f odt repertuarUngler1oo.tex`
`./make4ht-lib.lua:5: attempt to index global 'logging' (a nil value)`
The line 5 in the referenced file is
`local log = logging.new "make4ht-lib"`
On Debian testing the error is
`...texmf-dist/scripts/make4ht/filters/make4ht-domfilter.lua:2: module 'luaxml-domobject' not found:`

**Comment by michal-h21** [comment]
It seems that `luaxml-domobject` is included in the [texlive-luatex](https://packages.debian.org/buster/texlive-luatex) package. It seems that all `make4ht` files are in [texlive-extra-utils](https://packages.debian.org/buster/all/texlive-extra-utils/filelist), but `make4ht-logging.lua` is missing. It is included in vanilla TeX Live, so I think we can say that this file is missing only in Debian.

**Comment by jsbien** [comment]
Looks like make4ht-logging.lua in Debian it is available only in sid. I will make a virtual machine with sid and will make some tests.

**Comment by michal-h21** [comment]
Is it possible to make a bug report in Debian? This is fatal error, so I think they should want to fix it.

**Comment by jsbien** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990513

**Comment by jsbien** [comment]
> make4ht installed locally:
> `jsbien@JSBbuster:~/work/make4ht$ which make4ht`
> `/home/jsbien/.local/bin/make4ht`
> The debug option doesn't provide any additional information:
> `jsbien@JSBbuster:~/work/make4ht$ make4ht -a debug -uxc hej.cfg -f odt repertuarUngler1oo.tex`
> `./make4ht-lib.lua:5: attempt to index global 'logging' (a nil value)`
> The line 5 in the referenced file is
> `local log = logging.new "make4ht-lib"`
> Is "logging.new" a file? I don't have it anywhere on the disk. I also don't see it in your repository.

Let me remind that this problem occurs when the command is run in the current version of the repository, which contains make4ht-logging.lua. So the culprit is not a missing file (at least not this one).

**Comment by michal-h21** [comment]
Does your version of `/home/jsbien/.local/bin/make4ht` contain  the following line? 

     logging = require "make4ht-logging"

**Comment by jsbien** [comment]
Yes.

**Comment by michal-h21** [comment]
And does `kpsewhich make4ht-logging.lua` print a path to that file?

**Comment by jsbien** [comment]
`/home/jsbien/texmf/scripts/lua/make4ht/make4ht-logging.lua`

**Comment by michal-h21** [comment]
It is then really strange,  because `make4ht` loads `make4ht-logging.lua` and makes it globally available as `logging` library. It should be available in all loaded Lua files.

**Comment by jsbien** [comment]
I will make some additional tests in a day or so.

**Comment by jsbien** [comment]
A quick test on Debian bullseye (testing).
[bullseyeBAD.zip](https://github.com/michal-h21/make4ht/files/6757872/bullseyeBAD.zip)

**Comment by michal-h21** [comment]
Ah, that's lot of errors. Could you please make a MWE? Or post the log created with `-a debug` option?

**Comment by jsbien** [comment]
For now just the log. 
[bullseyeBAD1.zip](https://github.com/michal-h21/make4ht/files/6759419/bullseyeBAD1.zip)

**Comment by jsbien** [comment]
> It is then really strange, because `make4ht` loads `make4ht-logging.lua` and makes it globally available as `logging` library. It should be available in all loaded Lua files.
The logging problem does not occur if the document is typeset first with XeLaTeX. However there is another fatal error - cf. the enclosed log.
[buster+repository.zip](https://github.com/michal-h21/make4ht/files/6759521/buster%2Brepository.zip)

**Comment by michal-h21** [comment]
I think I will need TeX samples here, because I I cannot find the variable referenced in the first log file in TeX4ht sources at all. And the second log file reports error in biblatex.4ht, but the line that should cause that issue contains just comments.

**Comment by jsbien** [comment]
Thanks for your help!
