### ISSUE TITLE
html tables generated with wrong colspan

### ISSUE THREAD

**Issue by damageboy** [michal-h21/make4ht#48]
I'm trying to generate the riscv-isa-manual with make4ht.

All in all, I'm getting reasonable results with:
```
make4ht -d html -f html5+dvisvgm_hashes+common_domfilters riscv-spec.tex "htm,mathjax,2"
```

But in the resulting file, tables are generated with the wrong colspan, example:

![image](https://user-images.githubusercontent.com/125730/132983360-9e7c28cf-e1b1-4fb1-a6fa-7eb4cbf8586a.png)
The U-Type left most column is specifying the wrong colspan:

![image](https://user-images.githubusercontent.com/125730/132983384-a2e71e2a-c205-4cd8-b48e-af8c4445187d.png)

And if this is changed to `4` in this case:

![image](https://user-images.githubusercontent.com/125730/132983394-d86ea762-0c0b-4636-bb9d-fb63b5d8f6f1.png)

The tables is rendered properly.

**Comment by michal-h21** [comment]
Thanks for the report. Could you please make a MWE that I can test?

**Comment by damageboy** [comment]
Will attempt a MWE.

The [fix](https://github.com/michal-h21/make4ht/pull/49) I provided seems to work locally on the [riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/blob/master/src/riscv-spec.tex), but I assume you are after something more minimalistic than that.

**Comment by michal-h21** [comment]
Yes, it is quite long document, so it not easy to use it for debugging :)

**Comment by damageboy** [comment]
[mwe.tar.gz](https://github.com/michal-h21/make4ht/files/7150142/mwe.tar.gz)

Generate with:

```bash
make4ht -d html -f html5+dvisvgm_hashes+common_domfilters riscv-spec.tex "htm,mathjax,2"
```

**Comment by michal-h21** [comment]
I cannot reproduce this issue with TL 2021, the last line is aligned properly on my system. What is even stranger is that the `booktabs` DOM filter should fix only tables produced by the Booktabs package, so it shouldn't do anything with your document, as you don't seem to use this package at all. 

One thing that can cause issues is that you may need multiple compilations before all table columns get right. This depends on temporary files, so if you for example delete all temporary files before compilation, you may experience similar issues.

Anyway, I've found some other issues. The vertical rules are missing in the table produced by the MWE. Try the `html4.4ht` file from the attached `.zip` file, it should fix that. 

The `\instbitrange` command is displayed wrongly too, the numbers are not aligned properly. You can fix that using the following `.cfg` file. It also fixes the `commentary` environment, which produces wrong rule currently.

```
\Preamble{xhtml}
\renewenvironment{commentary}{\ifvmode\IgnorePar\fi\EndP\HCode{<div class="commentary">}\par\ShowPar}{\ifvmode\IgnorePar\fi\EndP\HCode{</div>}\par\ShowPar}
\renewcommand{\instbitrange}[2]{\HCode{<span class="instbitrange"><span class="instbitstart">}\instbit{#1}\HCode{</span><span class="instbitstop">}\instbit{#2}\HCode{</span></span>}}
\Css{div.commentary{font-size:0.9rem;font-style:italic;border-top:1px solid black;}}
\Css{body{max-width:70ch;margin: 1em auto;}}
[html4.zip](https://github.com/michal-h21/make4ht/files/7150309/html4.zip)

\Css{span.instbitrange{display: inline-block;min-width:3em;width:100\%;}}
\Css{span.instbitstart{display: inline-block;padding-left:0.2em;width:40\%;}}
\Css{span.instbitstop{display: inline-block;text-align:right;width:50\%;}}
\begin{document}
\EndPreamble


```

**Comment by michal-h21** [comment]
It seems that the zip file was not uploaded in my previous answer, so it is here: [html4.zip](https://github.com/michal-h21/make4ht/files/7150312/html4.zip)

**Comment by damageboy** [comment]
Thanks!
FWIW, I was trying to use the MikTex 21.6 docker image on linux when reproducing this.

**Comment by michal-h21** [comment]
Ah, if you use Docker container, you may need to run `make4ht` multiple times, because all temporary files are created from scratch for every use.

**Comment by damageboy** [comment]
:)

That is a very unepected turn of events :)

Trying with the `.cfg` file now. 
Seems like it already references the html4.zip file, so I wouldn't need to place it anywhere?

**Comment by damageboy** [comment]
With the cfg file provided and multiple runs inside docker I do get now this:

![image](https://user-images.githubusercontent.com/125730/133047949-72e37b0f-5090-4c5c-99f2-5335920ca0da.png)

The PDF looks like this (the main issue remaining is the vertical lines that are missing from the tables):

![image](https://user-images.githubusercontent.com/125730/133050105-ea110ba9-ccb7-4ecf-8e95-9ca56c9cdc54.png)

**Comment by michal-h21** [comment]
The markdown link to `html4.zip` in the config file listing was my mistake, it shouldn't be here. Here is an updated `.cfg` file that fixes also the vertical lines (so you don't need the updated `html4.4ht`):

```
\Preamble{xhtml}
\renewenvironment{commentary}{\ifvmode\IgnorePar\fi\EndP\HCode{<div class="commentary">}\par\ShowPar}{\ifvmode\IgnorePar\fi\EndP\HCode{</div>}\par\ShowPar}
\renewcommand{\instbitrange}[2]{\HCode{<span class="instbitrange"><span class="instbitstart">}\instbit{#1}\HCode{</span><span class="instbitstop">}\instbit{#2}\HCode{</span></span>}}
\Css{div.commentary{font-size:0.9rem;font-style:italic;border-top:1px solid black;}}
\Css{body{max-width:70ch;margin: 1em auto;}}

\Css{span.instbitrange{display: inline-block;min-width:3em;width:100\%;}}
\Css{span.instbitstart{display: inline-block;padding-left:0.2em;width:40\%;}}
\Css{span.instbitstop{display: inline-block;text-align:right;width:50\%;}}

\catcode`\:=11
\Configure{multicolumn}
   {\global\let\colCSS\empty
    \Configure{VBorder}
       {}
       {\xdef\colCSS{\colCSS
                     border-\ifnum \ar:cnt=0 left\else right\fi
                     :solid black 0.4pt;}%
       }{}{}%
   }
   {\ifx \colCSS\empty \else
        \Css{td\#TBL-\TableNo-\HRow-\HCol{\colCSS}}%
    \fi
   }
   {\ifvmode\IgnorePar\fi
    \HCode{<div class="multicolumn" }\HColAlign\HCode{>}%
    \ifx \colCSS\empty \else
        \Css{td\#TBL-\TableNo-\HRow-\HCol{\colCSS}}%
    \fi
   }
   {\ifvmode\IgnorePar\fi \EndP\HCode{</div>}}
\catcode`\:=12
\begin{document}
\EndPreamble

```

**Comment by damageboy** [comment]
Just circling back to report that the configuration file you provided works when running make4ht twice inside docker. Thanks for all the help, I will try to adapt the config if/when I see more issues that I can resolve myself :)

**Comment by michal-h21** [comment]
@damageboy that's great to hear. I am sure you will find more issues in your full book, similar to the `commentary` environment issue.
