### ISSUE TITLE
svg files don't fully respect --output-dir

### ISSUE THREAD

**Issue by AndrewMathas** [michal-h21/make4ht#5]
Thanks for all of your work on this! I've noticed a minor cosmetic issue with svg files.

Take the simple latex file `test.tex` given by
```
\documentclass{article}
\usepackage{pst-all}

\begin{document}

  \begin{pspicture}(0,-3)(12,5)
      \psline[linewidth=2pt]{->}(1.5,0)(0,0)
  \end{pspicture}

\end{document}
```
together with the `text.cfg` file
```
% We are generating HTML + MathML code
\Preamble{xhtml,mathml}

% Output HTML5 doctype instead of the default for HTML4
\Configure{DOCTYPE}{\HCode{<!doctype html>\Hnewline}}

% Custom page opening
\Configure{HTML}{\HCode{<html lang="en">\Hnewline}}{\HCode{\Hnewline</html>}}

% use svg for pstricks
\ConfigureEnv{psmatrix}{\Picture*{}}{\EndPicture}{}{}
\Configure{Picture}{.svg}

\begin{document}
\EndPreamble
```

Then the command `make4ht -d test -c test.cfg test.tex` correctly generates a web page that has  one svg image, which is correctly copied into the subdirectory test. However, a copy of the svg file is also kept in the current directory, which is necessary because the html uses the image in the current directory and not the copy in the test subdirectory.

A second, very minor issue, that I noticed is that `-build-file` doesn't use kpsewhich.

**Comment by michal-h21** [comment]
The `--output-dir` copies all output files to the destination directory, but it doesn't delete anything. So the `HTML`, `CSS` and image files are copies to the `test` directory, but they will also  remain in the source directory. It is sometimes useful, so I am not sure it is a bug.

Regarding the build files, the lookup uses `kpse` library, but they must be placed somewhere in the `scripts` tree, ie `~/texmf/scripts/lua/mymk4buildfiles`.

**Comment by AndrewMathas** [comment]
Thanks for the explanation Michal! I had assumed that the idea behind `--output-dir` was to clean things up. I only really care about images and I don't mind so much that copies stay in the original directory but, rather, that the html file links to the original files rather than the ones in the output directory. It's not a big deal as I can move them there myself and change the image links in the html file.

**Comment by michal-h21** [comment]
The `HTML` files in the output directory should link correctly to the images, don't they?

**Comment by AndrewMathas** [comment]
Hi Michal,

Apologies, I was thinking that your `--output-dir` was intended as a fix for the tex4ht `imgdir` command that you can put inside `\Preamble{...}`, which changes the links in the HTML file to point to a subdirectory but does not move the images. Previously I scripted around this by moving the images myself because the behaviour that I want is for the html file to stay in the current directory and all images to be in a subdirectory.

Your `--output-dir` command works as advertised. Please delete/close this thread.
Andrew
