### ISSUE TITLE
make4ht not expand function on math mode

### ISSUE THREAD

**Issue by danielezambelli** [michal-h21/make4ht#50]
make4ht don't compile correctly this .tex file (make4ht testmathbb.tex -l -u -s -d dist "mathjax"):

\documentclass[a4paper,10pt]{memoir}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts, amssymb}

%---------------------------------
% Functions definition
\newcommand{\N}{\ensuremath{\mathbb{N}}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\round}[1]{\left( #1 \right)}
\newcommand{\square}[1]{\left[ #1 \right]}
\newcommand{\intervac}[2]{\left]#1;~#2\right]}

\begin{document}

\section{Without functions}
Numerics sets:

\(\mathbb{N}\); \(\mathbb{Z}\); \dots

Expressions:
\[4x^2 +3x +2 = \left[\left(4x+3\right) \cdot x +2 \right]\]
Subset:
\[2 < x \leqslant 5 \Rightarrow \left]2;~5\right]\]

\section{With functions}
Numerics sets:

\(\N\); \(\Z\); \dots

Expressions:
\[4x^2 +3x +2 = \square{\round{4x+3} \cdot x +2}\]
Subsets:
\[2 < x \leqslant 5 \Rightarrow \intervac{2}{5}\]

\end{document}

**Comment by michal-h21** [comment]
I ran into an error, because your code was missing all math environments. This version compiles:

```
% https://github.com/michal-h21/make4ht/issues/50
\documentclass[a4paper,10pt]{memoir}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts, amssymb}

%---------------------------------
% Functions definition
\newcommand{\N}{\ensuremath{\mathbb{N}}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\round}[1]{\left( #1 \right)}
\renewcommand{\square}[1]{\left[ #1 \right]}
\newcommand{\intervac}[2]{\left]#1;~#2\right]}

\begin{document}

\section{Without functions}
Numerics sets:

\(\mathbb{N}\); \(\mathbb{Z}\); \dots

Expressions:
\[4x^2 +3x +2 = \left[\left(4x+3\right) \cdot x +2 \right]\]
Subset:
\[2 < x \leqslant 5 \Rightarrow \left]2;~5\right]\]

\section{With functions}
Numerics sets:

\(\N\); \(\Z\); \dots

Expressions:
\[4x^2 +3x +2 = \square{\round{4x+3} \cdot x +2}\]
Subsets:
\[2 < x \leqslant 5 \Rightarrow \intervac{2}{5}\]

\end{document}

```

Custom macros don't work out of the box, you must pass their definition to MathJax. You can use the [MathJaxConfig](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#x8-770007.19.3) configuration for that. The following configuration file works:

```
\Preamble{xhtml} 
\catcode`\#=11 
\Configure{MathJaxConfig}{{ 
    tex: { 
      tags: "ams", 
      \detokenize{% 
      macros: { 
        N: "\\mathbb{N}", 
        Z: "\\mathbb{Z}", 
        round: ["\\left(#1\\right)", 1],
        square: ["\\left[#1\\right]", 1],
        intervac: ["\\left]#1;~#2\\right]", 2],
      } 
  } 
} 
}} 
\catcode`\#=6 
\begin{document} 
\EndPreamble

```

**Comment by danielezambelli** [comment]
Thanks, it works well for me.

I'm having difficulty finding documentation on the format and commands available for the configuration file, where could I find it?

Daniele.

**Comment by michal-h21** [comment]
The documentation is unfortunately still quite sparse and spread over several places. I add the new information to the page I linked in my previous post. Much more information is still in the [original documentation](https://tug.org/tex4ht/doc/mn11.html#QQ1-11-51) (note that you can click on the numbers on the left side and it will show an example of use), and also [here](https://www.kodymirus.cz/src4ht/tex4ht-infoch2.html#tex4ht-infose1.html).
