### ISSUE TITLE
MiKTeX: "xtpipes failed trying tidy"

### ISSUE THREAD

**Issue by gl-utah** [michal-h21/make4ht#53]
I'm running MiKTeX on Windows 8.1.  Running `make4ht -f odt short1.tex` on the following "short1.tex" file
```
\documentclass{article}
\begin{document}ABC\end{document}
```
does produce a correct ODT file, but throws two warnings:
```
[STATUS] make4ht: Conversion started
[STATUS] make4ht: Input file: short1.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
entering extended mode
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
entering extended mode
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
entering extended mode
        1 file(s) moved.
[WARNING] xtpipes: xtpipes failed trying tidy
'tidy' is not recognized as an internal or external command.
[WARNING] xtpipes: Tidy failed as well
        1 file(s) moved.
        1 file(s) moved.
        1 file(s) moved.
        1 file(s) moved.
        1 file(s) moved.
        1 file(s) moved.
        1 file(s) copied.
[STATUS] make4ht: Conversion finished
```
I got several mistakes when converting a larger file, and before trying to troubleshoot them, I wonder if I should or should not ignore these "xtpipes" warnings.  On the larger file, I got these "xtpipes" warnings several times.

I could not find much information about these warnings.  I understood very little of `https://github.com/michal-h21/make4ht/blob/master/make4ht-xtpipes.lua` but based on it, perhaps it will help to know that the file tex4ht.jar (dated 4/20/2009) is in [...]AppData\Local\Programs\MiKTeX 2.9\tex4ht\bin and the file tex4ht.sty (dated 3/6/2021) is in [...]AppData\Local\Programs\MiKTeX 2.9\tex\generic\tex4ht.

**Comment by michal-h21** [comment]
It seems like the main issue is that `xtpipes` are not correctly executed. This tool fixes some issues in the XML files and especially handles hyperlinks, so you will most likely get broken ODT file without it. 

Could you run `make4ht -m draft -f odt -a debug short1.tex` and post the terminal output? It should print output from `xtpipes`.

**Comment by gl-utah** [comment]
I attach the terminal's output. 
[debugoutput.txt](https://github.com/michal-h21/make4ht/files/7614652/debugoutput.txt)
Line 252 says that java is not recognized.  After seeing that, I decided to install java, rebooted my computer, and that eliminated the problem!  It also eliminated the "xtpipes" problem in the larger file that I'm working on.  Many thanks!

**Comment by michal-h21** [comment]
Good catch, thanks. `make4ht` will print the output of the `xtpipes` command when it fails, in the next version.
