### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by wochristian** [michal-h21/make4ht#6]
When converting LaTex to html, images are embedded into html pages using the original width and height.  The width parameter is not respected.

\includegraphics[width=0.7\textwidth]{chapter1/figures/sine.png}

Is there a good way to set or limit the image size in the generated html pages?

**Comment by michal-h21** [comment]
As LaTeX in DVI mode, which is used in `tex4ht` compilation doesn't support most image formats, `tex4ht` doesn't know the image dimensions. It needs `.xbb` file for each image, where bounding box is stored. The `.xbb` file can be created using `ebb -x` command. Another option is to use `Gin-dim` option, it will use the dimensions used in `\includegraphics` options. But the `.xbb` file is preferred, as it will result in correct image size for images without explicit dimensions in `\includegraphics`.

**Comment by gnull** [comment]
What if my images are generated from pdf, which is in turn generated from a standalone tex file?

I'm building my standalione pdf beforehand and then including it in the main pdf document with `\includegraphics{my-file.pdf}`. It seem to confuse make4ht, the image on the generated pdf looks way too big. If I generate the xxb file manually with `ebb -x my-file.pdf` or with `ebb -x my-file-.png`, the images look too small.

What's the correct way to adding the `ebb` call to the make4ht compilation process?

**Comment by gnull** [comment]
Interestingly, the scale seems to be off by 2 times. If I do `\includegraphics[scale=2]{my-file.pdf}` (conditionally, only applying it in make4ht), it looks good.
