### ISSUE TITLE
Put odt file into output folder when using "--format odt -d myfolder" command

### ISSUE THREAD

**Issue by ThiloteE** [michal-h21/make4ht#69]
Yesterday, I updated to the newest development version of make4ht on miktex (version 0.3l) and it compiles odt again.

![grafik](https://user-images.githubusercontent.com/73715071/161264345-ac9bb102-795b-4fc4-8492-179f55919626.png)

compiling the MWE from https://github.com/michal-h21/make4ht/issues/58#issuecomment-1000961270 via lua > bibtex (biber) > lua > lua and then converting via `make4ht --format odt --lua -d odt --loglevel debug testthis.tex` the outcome is thus:

- [x] the MWE finishes the compilation successfully. ✔
- [x] the odt file is indeed created, and it looks fine! ✔
- [ ] the odt file is not in the output folder as specified with the option `-d odt`  (it should be within the folder "odt").

**Comment by michal-h21** [comment]
Thanks for the report. It seems that copying of the output files to the output directory happens before the ODT file is packed, so you will not get anything in the output directory in the first run, and then you will get older version of the ODT file. It should be fixed now in make4ht sources.

**Comment by ThiloteE** [comment]
Probably fixed by https://github.com/michal-h21/make4ht/commit/5b6e6e7048554006ef2aa77ee858a74493749f15, https://github.com/michal-h21/make4ht/commit/cdb150bc418dc966029c8b0112c4a4c10bec6afe and https://github.com/michal-h21/make4ht/commit/61e13aa31259303aae0697b7d6d069e404b84209

**Comment by michal-h21** [comment]
I hope so.
