### ISSUE TITLE
Request: preserve author labels as HTML tags

### ISSUE THREAD

**Issue by jhenin** [michal-h21/make4ht#7]
Hi!

We use htlatex to create HTML from LaTeX sources, and we would like to keep our internal hyperlinks permanent. So far we use a trick: a script that replaces the tags generated by tex4ht with the label used in the LaTeX source. That is only possible because of HTML comments created by tex4ht next to references:
`href="#x1-90004">4<!--tex4ht:ref: sec:something -->`
For now we parse those lines to get a mapping between our labels and the tags. Unfortunately those comments are only generated for `\ref{}` commands, which makes it impossible to define permanent links to labels that are not referenced within the document itself.

Is there a way to trick htlatex into providing this mapping for all labels, or even better, preserving them as tags to begin with?

Thanks!

**Comment by michal-h21** [comment]
One easy solution would be to create a script which would create TeX file with `\ref` commands for all `\label` commands in your source. You can include that file from your main document. Something like

     \ifdefined\HCode\input{reffile.tex}\fi

You can remove these references from the HTML file using another script, just put some HTML tags at the start and at the end:

     \HCode{<start-refs>}
     \ref{sec:something}
     ...
     \HCode{</start-refs>}

**Comment by jhenin** [comment]
Thank you, that was very helpful.
