### ISSUE TITLE
Question: How to browse 4ht files in source repository

### ISSUE THREAD

**Issue by ThiloteE** [michal-h21/make4ht#70]
When browsing [the source repository](https://svn.gnu.org.ua/viewvc/tex4ht/trunk/lit/) of make4ht, the website does not show .4ht files.
What can I do to have a look at them and download the newest version of these files?

**Comment by michal-h21** [comment]
No, `.4ht` files are not part of `make4ht`, they come form [TeX4ht](https://tug.org/tex4ht/). The source files are literate programming TeX files, from which `.4ht` files are created. They are [here](https://svn.gnu.org.ua/viewvc/tex4ht/trunk/lit/). The most important source file is [tex4ht-4ht.tex](https://svn.gnu.org.ua/viewvc/tex4ht/trunk/lit/tex4ht-4ht.tex?view=co&content-type=text%2Fplain), it is source for all .4ht files for packages. Other TeX files contain configurations for output format, so tex4ht-html4.tex contains configurations for HTML, tex4ht-oofffice.tex for the ODT output, etc.

The literate programming system is described a bit here: https://www.kodymirus.cz/tex4ht-doc/ForDevelopers.html

So the process is : 

1. copy relevant generated .4ht files to a directory with a test file
2. debug code
3. add changes to the literate TeX sources and update it to SVN
4. Karl Berry watches SVN, and when it changes, he generates .4ht files and pushes it directly to TeX Live. CTAN is not updated at all. MikTeX pulls changes from TeX Live.

**Comment by michal-h21** [comment]
Here is also the ChangeLog: https://tug.org/tex4ht/changelog.html

**Comment by ThiloteE** [comment]
Thanks!
