### ISSUE TITLE
Multiple tikzpicture calls in one paragraph

### ISSUE THREAD

**Issue by danielezambelli** [michal-h21/make4ht#71]
Hello!

I have encountered a new problem with tikz.

If I run tikzpicture in different paragraphs everything works as I expect, however if multiple tikzpictures are run in the same paragraph they are not correctly recognized.

A minimal example:
`
\documentclass[10pt,a4paper]{memoir}

\usepackage{tikz}
\usetikzlibrary{
  arrows,
  arrows.meta,
  matrix,}

\newcommand{\vectAB}[7][black]{% Vettore con etichette agli estremi.
  % Syntax: \vectAB[parametri]{pi}{pf}{posni}{nomei}{posnf}{nomef}
  % Example:
  %   \vectAB[green]{(8, 0)}{(12, 6)}{below left}{A}{above left}{B}
\begin{tikzpicture}[x=5mm, y=5mm, smooth]
  \draw [->, #1] #2 node [#4]{$#5$} -- #3 node [#6]{$#7$};
\end{tikzpicture}
}

\begin{document}
\vectAB[blue]{(8, 0)}{(12, 6)}{below left}{A}{above left}{B}

\vectAB[red]{(8, 0)}{(12, 6)}{below left}{C}{above left}{D}

\vectAB[blue]{(8, 0)}{(12, 6)}{below left}{E}{above left}{F}
\vectAB[red]{(8, 0)}{(12, 6)}{below left}{G}{above left}{H}        % Error

\end{document}
`
[tikzpicture.txt](https://github.com/michal-h21/make4ht/files/8403977/tikzpicture.txt)

Thanks for your attention.

Daniele

**Comment by michal-h21** [comment]
I get a correct result with current [dvisvgm4ht](https://github.com/michal-h21/dvisvgm4ht/blob/master/pgfsys-dvisvgm4ht.def) driver. This version is also included the development version of PGF, but it seems that the version on CTAN doesn't include these fixes, and it fails for multiple pictures in the paragraph. 

So the solution is to use https://github.com/michal-h21/dvisvgm4ht until PGF get an update in TeX distributions.

**Comment by danielezambelli** [comment]
Thanks!
