### ISSUE TITLE
package ulem

### ISSUE THREAD

**Issue by danielezambelli** [michal-h21/make4ht#72]
The package ulem does not seem to be supported by make4ht.

In text mode it produces incorrect results.

In math mode it does not recognize macros.

Is it possible to support it or is it better to use another package for underlining?

Miniexamle:

%--8<-------------------------------------
\documentclass[10pt,a4paper]{memoir}
\usepackage[T1]{fontenc} 
\usepackage{textcomp} 	
\usepackage[utf8]{inputenc}
\usepackage[italian]{babel} 

\RequirePackage{amsmath, amssymb, amsthm}% amsfonts è caricato da amssymb
\RequirePackage[e]{esvect} % per i vettori
\RequirePackage{physics}   % fisica e differenziale (dd)
\RequirePackage{cancel} % per le semplificazioni
\RequirePackage[normalem]{ulem} % sottolineature
\usepackage{lipsum}

\begin{document}

The commands of the package \verb|ulem| 
are misinterpreted in text mode while 
are not recognized in math mode.

Text mode:
\begin{itemize}
\item underline with \verb|\uline|: \uline{under-line}
\item duble underline with \verb|\uuline|: \uuline{dubleunder-line}
\item dashed underline with \verb|\dashuline|: \dashuline{dashedunder-line}
\item doted underline with \verb|\dotuline|: \dotuline{dotedunder-line}
\item wavey underline with \verb|\uwave|: \uwave{under-wave}
\item cancel with \verb|\sout|: \sout{cancel-line}
\item xcancel with \verb|\xout|: \xout{xcancel-line}
\end{itemize}

Math mode:
\[\uline{5a^3}\uuline{-4ab}+1\uwave{+2a^3}
  \dashuline{+2ab}-a\dotuline{-3a^3}\]

The errors occur with both:\\
mathml, \\
compiled with: 
\verb|make4ht ulem.tex -l -u -s -d dist "mathml"|\\
and mathjax, \\
compiled with: 
\verb|make4ht ulem.tex -c md_make4ht -l -u -s -d dist "mathjax"|.
\end{document}
%--8<-------------------------------------

Thanks

  Daniele

**Comment by danielezambelli** [comment]
Thanks for your work.

Is it possible to have a single configuration file that works for both mathjax and mathml with:

make4ht ulem.tex -c m4htulem -l -u -s -d dist "mathml"
make4ht ulem.tex -c m4htulem -l -u -s -d dist "mathjax"

I tried the following which works pretty well for mathjax (wave is rendered with a straight line), but gives an error for mathml:

%--8<-------------------------------------
make4ht ulem.tex -c m4htulem -l -u -s -d dist "mathml" 
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: ulem.tex
[WARNING] tocid: char-def module not found
[WARNING] tocid: cannot fix section id's
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename     Line    Message
[ERROR]   htlatex: ./m4htulem.cf        52       LaTeX Error: Missing 
\begin{document} in `m4htulem.cfg'.
%--8<-------------------------------------

and produces a result where dirty from the configuration file itself.

I tried with the following configuration file:

%--8<-------------------------------------
\Preamble{xhtml}
\Configure{uline}
   {\HCode{<span class="uline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{uline-math}
   {\HCode{<span class="uline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{.uline,.uline-math{ text-decoration:underline; }}
\Configure{uuline}
   {\HCode{<span class="uuline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{uuline-math}
   {\HCode{<span class="uuline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{.uuline,.uuline-math{ text-decoration:underline double; }}
\Configure{sout}
   {\HCode{<span class="sout">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{sout-math}
   {\HCode{<span class="sout">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{span.sout, .sout-math {text-decoration: line-through }}
\Configure{xout}
   {\HCode{<span class="xout">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{xout-math}
   {\HCode{<span class="xout-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.xout, .xout-math {text-decoration: line-through underline }}
\Configure{uwave}
   {\HCode{<span class="uwave">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{uwave-math}
   {\HCode{<span class="uwave-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.uwave, .uwave-math {text-decoration:underline wavy; }}
\Configure{dashuline}
   {\HCode{<span class="dashuline">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{dashuline-math}
   {\HCode{<span class="dashuline-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.dashuline, .dashuline-math {text-decoration:underline dashed;}}
\Configure{dotuline}
   {\HCode{<span class="dotuline">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{dotuline-math}
   {\HCode{<span class="dotuline-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.dotuline, .dotuline-math {text-decoration:underline dotted;}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Configurations for MathJax %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\catcode`\#=11 
\Configure{MathJaxConfig}{{ 
    tex: { 
      packages: {'[+]': ['html','enclose']},
      \detokenize{% 
      macros: { 
        % our sample macro takes a parameter 
        uline: ["\\enclose{bottom}{#1}",1], 
        uuline: ["\\enclose{bottom}{\\enclose{bottom}{#1}}",1], 
        uwave: ["\\enclose{bottom}{#1}",1], 
        sout: ["\\enclose{horizontalstrike}{#1}",1], 
        xout: ["\\enclose{bottom}{\\enclose{horizontalstrike}{#1}}",1], 
        dashuline: ["\\style{border-bottom:1px dashed black;}{#1}",1], 
        dotuline: ["\\style{border-bottom:1px dotted black;}{#1}",1], 
      } 
  } 
} 
}} 
\catcode`\#=6 
\begin{document}
\EndPreamble
%--8<-------------------------------------

**Comment by michal-h21** [comment]
The `\Configure{MathJaxConfig}` is defined only in the plain MathJax mode, not with MathML. When it is not defined, you will get an error, because the argument to the configuration will be printed to the document.

You can test for it's existence using:

     \ifcsname a:MathJaxConfig\endcsname
        code for Mathjax
    \else
        code for MathML
    \fi

**Comment by danielezambelli** [comment]
The following configuration file seems to work fine to me.

Thanks.

%--8<-------------------------------------

\Preamble{xhtml}

\Configure{uline}
   {\HCode{<span class="uline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{uline-math}
   {\HCode{<span class="uline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{.uline,.uline-math{ text-decoration:underline; }}
\Configure{uuline}
   {\HCode{<span class="uuline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{uuline-math}
   {\HCode{<span class="uuline">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{.uuline,.uuline-math{ text-decoration:underline double; }}
\Configure{sout}
   {\HCode{<span class="sout">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Configure{sout-math}
   {\HCode{<span class="sout">}\NoFonts} {\EndNoFonts\HCode{</span>}}
\Css{span.sout, .sout-math {text-decoration: line-through }}
\Configure{xout}
   {\HCode{<span class="xout">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{xout-math}
   {\HCode{<span class="xout-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.xout, .xout-math {text-decoration: line-through underline }}
\Configure{uwave}
   {\HCode{<span class="uwave">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{uwave-math}
   {\HCode{<span class="uwave-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.uwave, .uwave-math {text-decoration:underline wavy; }}
\Configure{dashuline}
   {\HCode{<span class="dashuline">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{dashuline-math}
   {\HCode{<span class="dashuline-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.dashuline, .dashuline-math {text-decoration:underline dashed;}}
\Configure{dotuline}
   {\HCode{<span class="dotuline">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Configure{dotuline-math}
   {\HCode{<span class="dotuline-math">}\NoFonts} 
   {\EndNoFonts\HCode{</span>}}
\Css{span.dotuline, .dotuline-math {text-decoration:underline dotted;}}

\ifcsname a:MathJaxConfig\endcsname
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Configurations for MathJax %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\catcode`\#=11 
\Configure{MathJaxConfig}{{ 
    tex: { 
      packages: {'[+]': ['html','enclose']},
      \detokenize{% 
      macros: { 
        % our sample macro takes a parameter 
        uline: ["\\enclose{bottom}{#1}",1], 
        uuline: ["\\enclose{bottom}{\\enclose{bottom}{#1}}",1],  
%         uwave: ["#1",1], 
%         uwave: ["\\enclose{bottom}{#1}",1],
        uwave: ["\\style{border-bottom:1px underline wavy black;}{#1}",1], 
        sout: ["\\enclose{horizontalstrike}{#1}",1], 
        xout: ["\\enclose{bottom}{\\enclose{horizontalstrike}{#1}}",1], 
        dashuline: ["\\style{border-bottom:1px dashed black;}{#1}",1], 
        dotuline: ["\\style{border-bottom:1px dotted black;}{#1}",1], 
      } 
  } 
} 
}} 
\catcode`\#=6 

\else

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% code for MathML            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\fi

\begin{document}
\EndPreamble

%--8<-------------------------------------

**Comment by michal-h21** [comment]
I am glad it works for you now. I hope I can close this now.
