### ISSUE TITLE
tcolorbox references and aspect

### ISSUE THREAD

**Issue by danielezambelli** [michal-h21/make4ht#75]
Hi Michal,

There are some errors in the references with tcolorboxes.

And also the boxes are not drawn in the same way, but this is a secondary problem.

In the working file, mk4ht reports me errors related to the .aux file errors that are not raised in the minimal example.

I send you a minimal example:

%--8<-------------------------------------------------------
\documentclass[10pt,a4paper]{memoir}
\usepackage[T1]{fontenc} 
\usepackage[utf8]{inputenc} 
\usepackage[italian]{babel} 
\usepackage{amsmath, amssymb, amsthm}
\usepackage{ulem}
\RequirePackage[colorlinks, hyperindex, pagebackref,
                linkcolor=blue, filecolor=blue,
                citecolor = black, urlcolor=blue]{hyperref}

\usepackage{tcolorbox}
\tcbuselibrary{most}
\usepackage{lipsum}

\theoremstyle{plain}

\newcommand{\coloross}{violet}

\tcbset{
ossstyle/.style={fonttitle=\bfseries\upshape, fontupper=\slshape,
arc=0mm, colback=\coloross!5!white, colframe=\coloross!50!black,
theorem style=plain, coltitle=\coloross!30!black}
}

\newtcbtheorem[number within=chapter]{osservazione}{Osservazione}
              {ossstyle}{oss}

\begin{document}

\chapter{Problem with tcolorbox references}

\paragraph{Osservazioni}
Due ambienti per le osservazioni.

\begin{osservazione}{Osservazione interessante}{osser}
Questo è il contenuto di una osservazione interessante.
\end{osservazione}

There may be a reference to the observation in the text: \\
observation number: \ref{oss:osser};\\
title of the observation: \nameref{oss:osser};\\
observation page: \pageref{oss:osser}.

\lipsum[1-3]

\begin{osservazione}{Osservazione molto interessante}{primaoss}
Questo è il contenuto di una osservazione.
\end{osservazione}

There may be a reference to the observation in the text: \\
observation number: \ref{oss:primaoss};\\
title of the observation: \nameref{oss:primaoss};\\
observation page: \pageref{oss:primaoss}.

\end{document}
%--8<-------------------------------------------------------

Thank you for your attention.

  Daniele

**Comment by danielezambelli** [comment]
Dear Michal,

With this new version of the driver, the reference to the number works, but not the reference to the name (the page reference, of course, is not meaningful).

Complicating the example a bit (see below) I get strange errors:
 
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename     Line    Message
[ERROR]   htlatex: ./tcolorboxref.tex   50       Undefined control sequence.
[ERROR]   htlatex: ./tcolorboxref.tex   51       Package inputenc Error: inputenc is not designed for xetex or luatex.

Strange because 
- they are raised only for two lines of code and not for the other equal ones, 
- they concern lines that were previously compiled without problems.

New example:

%--8<-------------------------------------------------------
\documentclass[
10pt,a4paper]{memoir}
\usepackage[T1]{fontenc} 
\usepackage[utf8]{inputenc} 
\usepackage[italian]{babel} 
\usepackage{amsmath, amssymb, amsthm}
\usepackage{ulem}
\RequirePackage[colorlinks, hyperindex, pagebackref,
                linkcolor=blue, filecolor=blue,
                citecolor = black, urlcolor=blue]{hyperref}

\usepackage{tcolorbox}
\tcbuselibrary{most}
\usepackage{lipsum}

\theoremstyle{plain}

\newcommand{\coloross}{violet}
\newcommand{\colortcblist}{green}

\DeclareTCBListing{latexlistingbox}{ s O{} m }{%
colback = \colortcblist!5!white,
colframe = \colortcblist!75!black,
fonttitle = \bfseries,
IfBooleanTF = {#1}{}{listing side text},
title={#3},#2}

\tcbset{
ossstyle/.style={fonttitle=\bfseries\upshape, fontupper=\slshape,
arc=0mm, colback=\coloross!5!white, colframe=\coloross!50!black,
theorem style=plain, coltitle=\coloross!30!black}
}

\newtcbtheorem[number within=chapter]{osservazione}{Osservazione}
              {ossstyle}{oss}

\begin{document}

\chapter{Problem with tcolorbox references}

\paragraph{Osservazioni}
Due ambienti per le osservazioni.

\begin{osservazione}{Osservazione interessante}{primaoss}
Questo è il contenuto di una osservazione interessante.
\end{osservazione}

There may be a reference to the observation in the text: \\
observation number: \ref{oss:primaoss};\\
title of the observation: \nameref{oss:primaoss};\\
observation page: \pageref{oss:primaoss}.

\lipsum[1-3]

\begin{osservazione}{Osservazione molto interessante}{secondaoss}
Questo è il contenuto di una osservazione.
\end{osservazione}

There may be a reference to the observation in the text: \\
observation number: \ref{oss:secondaoss};\\
title of the observation: \nameref{oss:secondaoss};\\
observation page: \pageref{oss:secondaoss}.

\lipsum[4-5]

\begin{latexlistingbox}*{Osservazione}
\begin{osservazione}{Osservazione molto molto interessante}{terzaoss}
Questo è il contenuto di una osservazione.
\end{osservazione}

There may be a reference to the observation in the text: \\
observation number: \ref{oss:terzaoss};\\
title of the observation: \nameref{oss:terzaoss};\\
observation page: \pageref{oss:terzaoss}.
\end{latexlistingbox}

\end{document}
%--8<-------------------------------------------------------

**Comment by michal-h21** [comment]
I've found that you get the same error even when you compile your file using `lualatex`, so it seems more like a bug in Listings, which expects `\inputencodingname` to exists.

**Comment by danielezambelli** [comment]
Yes, if I compile without "-l", make4ht works fine.

I try to investigate the source of the error with LuaLaTeX.

Thank you.

**Comment by michal-h21** [comment]
I am glad it works now. I think that the Inputenc package shouldn't be necessary in recent LaTeX, as it expects UTF8 encoding even with PDFLaTeX.
