### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by mathsbeauty** [michal-h21/make4ht#8]
I followed the guide for installation of make4ht on windows (miktex+winedt) on the[ link ](https://d800fotos.wordpress.com/2015/01/19/create-e-books-from-latex-tex-files-ebook-aus-latex-tex-dateien-erstellen)
I could not find the file tex4ebook.lua as mentioned in this guide.  Where is the appropriate documentation for the installation of make4ht on windows?

**Comment by michal-h21** [comment]
The stable versions of `make4ht` and `tex4ebook` are included in Miktex. I don't use Miktex personally, but I think that you can install it using it's package manager. If you really want to install them manually, then you need to download and install [tex4ebook](https://github.com/michal-h21/tex4ebook) as well.
