### ISSUE TITLE
Question on customized template

### ISSUE THREAD

**Issue by huijunchen9260** [michal-h21/make4ht#82]
Dear Michal:

Is it possible to let make4ht to insert some chunk of HTML code to match the theme of my website? Like the custom footer so that the article would also have homepage button something like that.

HJ

**Comment by michal-h21** [comment]
Dear HJ,

you can use the `\Configure{@BODY}` and `\Configure{@/BODY}` commands to add some stuff at the page beginning and at the end. Try this configuration file:

```
\Preamble{xhtml}
\Configure{@BODY}{\ifvmode\IgnorePar\fi\EndP\HCode{<div>Some code at the beginning</div>}}
\Configure{@/BODY}{\ifvmode\IgnorePar\fi\EndP\HCode{<div>Some code at the end</div>}}
\begin{document}
\EndPreamble

```

Info about these configurations is [here](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#html-header). The `\IgnorePar\ and `\EndP` command are necessary for the correct handling of paragraphs, see this [section](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#paragraph-handling)

**Comment by huijunchen9260** [comment]
That is pretty helpful! I also want to know whether it is possible to include the external HTML file into the config file. For example, 

```tex
\Preamble{xhtml}
\Configure{@BODY}{\ifvmode\IgnorePar\fi\EndP\HCode{<div>expenad code from external html file</div>}}
\Configure{@/BODY}{\ifvmode\IgnorePar\fi\EndP\HCode{<div>expand code from external html file</div>}}
\begin{document}
\EndPreamble
```

So that after using static site generate this html page will also have proper header and footer that I intended.

Thank you!

**Comment by michal-h21** [comment]
Unfortunately, inclusion of external HTML is not supported. But if you want to use static site generators, you may be interested in the static site extension. See [this blog](https://www.kodymirus.cz/testblog/) for example.

**Comment by huijunchen9260** [comment]
That's nice, yet I am using [blogit](https://pedantic.software/git/blogit), a very minimalist static site generator to display all my files, so I am not sure whether I am incorporate the make4ht to all of my webpage, yet if only serve for the HTML version of the pdf file, I believe make4ht/tex4ht is still an amazing software!

This is [my application](https://huijunchen9260.github.io/pdf/IntermediateMacroAutumn2022/syllabus/syllabus.html).
