### ISSUE TITLE
'mathml,mathjax' not compiling complex indices without curly brackets

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#85]
$\LaTeX$ allows writing complex indices like `$x_\mathbb{R}$` ($x_\mathbb{R}$) without curly brackets as the code is unambiguous. When I compile such expressions using
`make4ht file.tex`
everything works fine. As soon as I turn on mathml,mathjax mode:
`make4ht file.tex 'mathml,mathjax'`
make4ht breaks down.

Note: file tex is a minimal file containing `$x_\mathbb{R}$`.

**Comment by michal-h21** [comment]
This is one issue that it not easily fixable, unfortunately. See [this page](https://www.kodymirus.cz/tex4ht-doc/Howto.html#subscripts-and-superscripts) for more details. It contains a Lua script that tries to pre-process the file, and to add the brackets before passing to `make4ht`.

**Comment by yalguzaq** [comment]
Understood, thanks!
