### ISSUE TITLE
'mathml'-option does not produce correct output for $\implies$ and $\impliedby$

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#86]
Compiling a file containing the commands `$\implies$` ($\implies$) and `$\impliedby$` ($\impliedby$) via normal command
`make4ht markup.tex`
produces the desired result, whereas 
`make4ht markup.tex 'mathml,mathjax'`
shows the weird output.

Note: minimal latex file only contains `$\implies$` and `$\impliedby$`.

**Comment by michal-h21** [comment]
Thanks for the report. It seems that wrong Unicode character is used for `\Longrightarrow`, and `\Lonfleftarrow` is not handled at all. I will fix that in TeX4ht sources, in the meantime, you can use this configuration file:
```

\Preamble{xhtml}
\MathSymbol\mathrel{Longleftarrow}
\Configure{Longrightarrow}        {\expandafter\csname x:unicode\endcsname{27F9}}
\Configure{Longleftarrow}         {\expandafter\csname x:unicode\endcsname{27F8}}
\begin{document}
\EndPreamble
```

**Comment by yalguzaq** [comment]
One more thing, could you also redefine `\iff`? Thank you very much!

**Comment by michal-h21** [comment]
Sure. I've found that there is more issues for long arrows, so I fixed them too.
