### ISSUE TITLE
tabular environment produces exceedingly long column lines

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#88]
The following table
```
  \begin{table}
    \begin{tabular}{|c|ccccc|}
      \hline
      & $\cdots$ & ${x_i}$ & $\cdots$ & ${x_j}$ & $\cdots $\\
      \hline
      & $\cdots$ & ${0}$ & $\cdots$ & ${\bar{c}_j}$ & $\cdots$ \\
      \hline
      $\vdots$ & $\vdots$  & ${\vdots}$  & $\vdots$ & ${\vdots}$  & $\vdots$\\[5pt]
      ${x_{B(l)} = x_i}$ & $\vdots$  & ${1}$  & $\vdots$ & ${u_l}$ & $\vdots$ \\[5pt]
      $\vdots$ & $\vdots$ & ${\vdots}$ & $\vdots$ & ${\vdots}$  & $\vdots$\\[5pt]
      \hline
    \end{tabular}
  \end{table}
```
when run by pdflatex produces the following output
![image](https://user-images.githubusercontent.com/116675649/197878733-ae41e184-b466-4e5f-9947-a2bbd6c21233.png)

Doing the same via `make4ht file.tex 'mathml'` or `make4ht file.tex` produces the following weird footer:
![image](https://user-images.githubusercontent.com/116675649/197879109-b2e28e25-9a25-4a03-a49d-4e63f5d44fb7.png)

**Comment by michal-h21** [comment]
Thanks for the report. The extra row is caused by the extra row that is inserted after `\hline`. Try this configuration file:

```
\Preamble{xhtml}
\Css{.hline + .vspace:last-child{display:none;}}
\begin{document}
\EndPreamble

```

**Comment by yalguzaq** [comment]
Thanks a lot for correcting these bugs that quickly, really helpful (I use your system dynamically for a live web app).
