### ISSUE TITLE
'mathml'-option messes up the matrix width

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#91]
Consider the following equation in the minimal LaTeX settings:
`$$\tilde{\mathbf{x}} := \begin{bmatrix} \dfrac{1}{nU}\mathbf{x}\\[7.5pt] \displaystyle 1 - \dfrac{1}{nU}\sum_{i=1}^{n}x_i\end{bmatrix} \in \mathfrak{R}^{n+1}.$$`
compiling it with
`make4ht file.tex`
produces the desired output
![image](https://user-images.githubusercontent.com/116675649/198370571-736bd936-98a8-4212-9e9e-4ec9c9d6a0e5.png)
whereas compiling it with 
`make4ht file.tex 'mathml,mathjax'`
messes up the matrix
![image](https://user-images.githubusercontent.com/116675649/198370634-b3159058-12a4-480e-a13f-c76af2fdabb8.png)

**Comment by michal-h21** [comment]
Thanks for the report. It is caused by `<mtd>` elements inside `<mtr class="array-vspace">`. It seems that this `<mtr>` shouldn't contain any children. I've fixed it in TeX4ht sources, so it should be available in TeX Live soon.
