### ISSUE TITLE
'mathml'-option does not ignore \\ in an matrix or array when the following line is empty

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#93]
When compiling
```
$$\begin{bmatrix}
    T & 0 \\
    0 & 1 \\
\end{bmatrix}$$
```
with `pdflatex` or `make4ht file.tex`, the output is correct as the engine recognizes that after \\\\ there is nothing filled in. 
![image](https://user-images.githubusercontent.com/116675649/198713921-942c32fa-602e-4943-9f72-5c6766df091c.png)

Using
`make4ht markup.tex 'mathml,mathjax'`
results in
![image](https://user-images.githubusercontent.com/116675649/198713662-7ae995af-eaf4-4fe6-88b9-22f67d4fe06b.png)

More generally, why does adding 'mathml' destroy the output so often? Don't they use the same logic?

**Comment by yalguzaq** [comment]
Thanks a lot. I'm closing the issue then. One question though: how do I update to the latest version of `make4ht`? I am running a web app based on `make4ht` so I need the latest version on the server.

**Comment by michal-h21** [comment]
I should release a new version soon. Or you can install it from make4ht Github, but I don't know how viable it is in your case.
