### ISSUE TITLE
Outputing weird \mathcal characters

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#95]
Every LaTeX engine (pdflatex) and other processors (MathJax TeX -> SVG) compile the following code
```
\begin{align*}
  \mathcal{A} \ \mathcal{B} \ \mathcal{C}\\
  \mathcal{D} \ \mathcal{E} \ \mathcal{F}\\
  \mathcal{G} \ \mathcal{H} \ \mathcal{I}
\end{align*}
```
into something like
![image](https://user-images.githubusercontent.com/116675649/198900470-b97e689b-f823-40a3-936f-1a49b17505c6.png)
`make4ht`, however, outputs these:
![image](https://user-images.githubusercontent.com/116675649/198900483-2f67a3e7-d47b-498d-8124-887260a485c0.png)
Interestingly, adding `'mathml,mathjax'`-option results in something different completely:
![image](https://user-images.githubusercontent.com/116675649/198900521-bfdcb84c-bb87-44c6-b878-5046f1412e7b.png)

My question is: would it be possible to stick with the classic `\mathcal` output per default? Is there a .cfg-solution to this problem? My priority is 'mathml'-version of the output.

**Comment by michal-h21** [comment]
TeX4ht outputs Unicode values for `\mathcal` characters, but the problem is that Unicode doesn't declare all possible characters, see the table [on this page](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols). It seems that Browser displays them wrongly. 

Regarding the MathML output, I get this output with MathJax rendering; with the regular Firefox rendering it displays correctly, even `B`. 

Anyway, the following version of `\mathcal` seems to work in both MathJax and default rendering:

```
\Preamble{xhtml}
\catcode`\:=11
\renewcommand\mathcal[1]{\HCode{<\a:mathml mi\Hnewline mathvariant="script">}#1\HCode{</\a:mathml mi>}}
\catcode`\:=12

\begin{document}
\EndPreamble

```

If it works, I can add something similar to TeX4ht sources.

**Comment by yalguzaq** [comment]
Unfortunately, this did not solve the problem. Furthermore, the preamble above caused some conflicts, for instance, I got an error with the following code (otherwise it works though):
```
If $X = \left\{a,b,c\right\}$, let
\begin{gather*}
\mathcal{T}_{1} = \left\{\varnothing, X, \left\{a\right\}, \left\{a,b\right\}\right\} \hspace{1cm} \text{and} \hspace{1cm} \mathcal{T}_{2} = \left\{\varnothing, X, \left\{a\right\}, \left\{b,c\right\}\right\} \,.
\end{gather*}
Find the smallest topology containing $\mathcal{T}_{1}$ and $\mathcal{T}_{2}$, and the largest topology contained in $\mathcal{T}_{1}$ and $\mathcal{T}_{2}$.  
```
It shows
![image](https://user-images.githubusercontent.com/116675649/199606629-cb0ef7c0-644f-45b2-8d60-5923d8484285.png)

**Comment by michal-h21** [comment]
It seems that we need to add extra group around it:

```
\Preamble{xhtml}
\catcode`\:=11
\renewcommand\mathcal[1]{\bgroup\HCode{<\a:mathml mi\Hnewline mathvariant="script">}#1\HCode{</\a:mathml mi>}\egroup}
\catcode`\:=12

\begin{document}
\EndPreamble
```

**Comment by yalguzaq** [comment]
I am still getting outputs like
![image](https://user-images.githubusercontent.com/116675649/199958126-b175f062-12fc-41a1-b16b-11942d8e9883.png)

This did not happen when I was using the tex-to-chtml converter by MathJAX, so are you sure that this is a browser issue? I tried this on several machines, the signs look weird on all of them.

**Comment by michal-h21** [comment]
I think this is an MathJax issue, that they use a strange font for `mathvariant="script"`. If you display it just in Firefox without MathJax, it looks how it should look according to [MDN](https://developer.mozilla.org/en-US/docs/Web/MathML/Global_attributes/mathvariant). 

I've toke a look at the MathML code generated by MathJax, and it seems that it uses `mathvariant="script"` too, but in addition, they also use  `data-mjx-variant="-tex-calligraphic"`. So you can try this:

```
\Preamble{xhtml}
\catcode`\:=11
\renewcommand\mathcal[1]{\bgroup\HCode{<\a:mathml mi\Hnewline  data-mjx-variant="-tex-calligraphic" mathvariant="script">}#1\HCode{</\a:mathml mi>}\egroup}
\catcode`\:=12
\begin{document}
\EndPreamble
```

**Comment by yalguzaq** [comment]
Yes, I can now confirm that this solution works. 

I think it makes sense to make this behaviour default in the next `make4ht` version.

**Comment by michal-h21** [comment]
The problem is that it is a proprietary MathJax attribute, and it could cause issues in other outputs that use MathML too (ODT, JATS, for example). It seems weird why MathJax doesn't use the correct font by default.
