### ISSUE TITLE
'mathml'-option produces long vertical line

### ISSUE THREAD

**Issue by yalguzaq** [michal-h21/make4ht#97]
**LaTeX:**
`$$\left({\bf E}|X|^p\right)^{\frac{q}{p}} \leq {\bf E} |X|^q$$`

**Compilation command:**
`make4ht markup.tex 'mathml,mathjax'`

**Erroneous output:**
![image](https://user-images.githubusercontent.com/116675649/200186696-824f40bc-e339-4ade-a0e1-0fcef9da2b38.png)
![image](https://user-images.githubusercontent.com/116675649/200187072-6ea0d28f-8cc9-4dec-8da4-65fb6a5f31ba.png)

**Correct output**:
![image](https://user-images.githubusercontent.com/116675649/200186857-c8cded63-fd79-410e-b096-83925a29c7f1.png)

**The problem summary:**
The absolute value line on the left is too long

**Comment by michal-h21** [comment]
In this case, just the right `|` character is used as the superscript base. You need to use `{|X|}` instead of just `|X|`.

**Comment by yalguzaq** [comment]
But this is not a standard LaTeX behaviour, no one uses `|` for superscripts. Furthermore, the problem only appears within the `mathml` context.

Considering how widespread the usage of `|` is for absolute value brackets, would it be possible to fix this in a new version of `make4ht`? Is there a temporary `cfg` fix?

**Comment by michal-h21** [comment]
The problem is that it is impossible at the TeX level to detect superscript base without proper grouping. You either use group, or only the last token is used. In the PDF output this error doesn't cause problems, because it is visually correct. In MathML, you need to correctly mark the base, and it is impossible without proper user input.

**Comment by michal-h21** [comment]
I've just realized that you can use an MathML attribute `stretchy` to disable stretching of the bar.  It seems that MathJax uses it as well. I still think it is better to correctly mark the superscript base, but with this change, the visual output will be the same.

Try this config file:

```
\Preamble{xhtml}
\Configure{MathClass}{3}{*}{<mo class="MathClass-rel" stretchy="false">}{</mo>}{}
\begin{document}
\EndPreamble

```

**Comment by yalguzaq** [comment]
Yes, this works perfectly! I hope this will become the default behaviour.
